package com.key.dwsurvey.pojo;

import java.io.Serializable;

public class AnCompChenRadio implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_an_comp_chen_radio.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_an_comp_chen_radio.belong_answer_id
     *
     * @mbggenerated
     */
    private String belongAnswerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_an_comp_chen_radio.belong_id
     *
     * @mbggenerated
     */
    private String belongId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_an_comp_chen_radio.qu_col_id
     *
     * @mbggenerated
     */
    private String quColId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_an_comp_chen_radio.qu_id
     *
     * @mbggenerated
     */
    private String quId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_an_comp_chen_radio.qu_option_id
     *
     * @mbggenerated
     */
    private String quOptionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_an_comp_chen_radio.qu_row_id
     *
     * @mbggenerated
     */
    private String quRowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_an_comp_chen_radio.visibility
     *
     * @mbggenerated
     */
    private Integer visibility;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_an_comp_chen_radio
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_an_comp_chen_radio.id
     *
     * @return the value of t_an_comp_chen_radio.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_an_comp_chen_radio.id
     *
     * @param id the value for t_an_comp_chen_radio.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_an_comp_chen_radio.belong_answer_id
     *
     * @return the value of t_an_comp_chen_radio.belong_answer_id
     *
     * @mbggenerated
     */
    public String getBelongAnswerId() {
        return belongAnswerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_an_comp_chen_radio.belong_answer_id
     *
     * @param belongAnswerId the value for t_an_comp_chen_radio.belong_answer_id
     *
     * @mbggenerated
     */
    public void setBelongAnswerId(String belongAnswerId) {
        this.belongAnswerId = belongAnswerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_an_comp_chen_radio.belong_id
     *
     * @return the value of t_an_comp_chen_radio.belong_id
     *
     * @mbggenerated
     */
    public String getBelongId() {
        return belongId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_an_comp_chen_radio.belong_id
     *
     * @param belongId the value for t_an_comp_chen_radio.belong_id
     *
     * @mbggenerated
     */
    public void setBelongId(String belongId) {
        this.belongId = belongId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_an_comp_chen_radio.qu_col_id
     *
     * @return the value of t_an_comp_chen_radio.qu_col_id
     *
     * @mbggenerated
     */
    public String getQuColId() {
        return quColId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_an_comp_chen_radio.qu_col_id
     *
     * @param quColId the value for t_an_comp_chen_radio.qu_col_id
     *
     * @mbggenerated
     */
    public void setQuColId(String quColId) {
        this.quColId = quColId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_an_comp_chen_radio.qu_id
     *
     * @return the value of t_an_comp_chen_radio.qu_id
     *
     * @mbggenerated
     */
    public String getQuId() {
        return quId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_an_comp_chen_radio.qu_id
     *
     * @param quId the value for t_an_comp_chen_radio.qu_id
     *
     * @mbggenerated
     */
    public void setQuId(String quId) {
        this.quId = quId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_an_comp_chen_radio.qu_option_id
     *
     * @return the value of t_an_comp_chen_radio.qu_option_id
     *
     * @mbggenerated
     */
    public String getQuOptionId() {
        return quOptionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_an_comp_chen_radio.qu_option_id
     *
     * @param quOptionId the value for t_an_comp_chen_radio.qu_option_id
     *
     * @mbggenerated
     */
    public void setQuOptionId(String quOptionId) {
        this.quOptionId = quOptionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_an_comp_chen_radio.qu_row_id
     *
     * @return the value of t_an_comp_chen_radio.qu_row_id
     *
     * @mbggenerated
     */
    public String getQuRowId() {
        return quRowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_an_comp_chen_radio.qu_row_id
     *
     * @param quRowId the value for t_an_comp_chen_radio.qu_row_id
     *
     * @mbggenerated
     */
    public void setQuRowId(String quRowId) {
        this.quRowId = quRowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_an_comp_chen_radio.visibility
     *
     * @return the value of t_an_comp_chen_radio.visibility
     *
     * @mbggenerated
     */
    public Integer getVisibility() {
        return visibility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_an_comp_chen_radio.visibility
     *
     * @param visibility the value for t_an_comp_chen_radio.visibility
     *
     * @mbggenerated
     */
    public void setVisibility(Integer visibility) {
        this.visibility = visibility;
    }
}