package com.key.dwsurvey.pojo;

import java.io.Serializable;

public class AnYesno implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_an_yesno.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_an_yesno.belong_answer_id
     *
     * @mbggenerated
     */
    private String belongAnswerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_an_yesno.belong_id
     *
     * @mbggenerated
     */
    private String belongId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_an_yesno.qu_id
     *
     * @mbggenerated
     */
    private String quId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_an_yesno.visibility
     *
     * @mbggenerated
     */
    private Integer visibility;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_an_yesno.yesno_answer
     *
     * @mbggenerated
     */
    private String yesnoAnswer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_an_yesno
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_an_yesno.id
     *
     * @return the value of t_an_yesno.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_an_yesno.id
     *
     * @param id the value for t_an_yesno.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_an_yesno.belong_answer_id
     *
     * @return the value of t_an_yesno.belong_answer_id
     *
     * @mbggenerated
     */
    public String getBelongAnswerId() {
        return belongAnswerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_an_yesno.belong_answer_id
     *
     * @param belongAnswerId the value for t_an_yesno.belong_answer_id
     *
     * @mbggenerated
     */
    public void setBelongAnswerId(String belongAnswerId) {
        this.belongAnswerId = belongAnswerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_an_yesno.belong_id
     *
     * @return the value of t_an_yesno.belong_id
     *
     * @mbggenerated
     */
    public String getBelongId() {
        return belongId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_an_yesno.belong_id
     *
     * @param belongId the value for t_an_yesno.belong_id
     *
     * @mbggenerated
     */
    public void setBelongId(String belongId) {
        this.belongId = belongId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_an_yesno.qu_id
     *
     * @return the value of t_an_yesno.qu_id
     *
     * @mbggenerated
     */
    public String getQuId() {
        return quId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_an_yesno.qu_id
     *
     * @param quId the value for t_an_yesno.qu_id
     *
     * @mbggenerated
     */
    public void setQuId(String quId) {
        this.quId = quId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_an_yesno.visibility
     *
     * @return the value of t_an_yesno.visibility
     *
     * @mbggenerated
     */
    public Integer getVisibility() {
        return visibility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_an_yesno.visibility
     *
     * @param visibility the value for t_an_yesno.visibility
     *
     * @mbggenerated
     */
    public void setVisibility(Integer visibility) {
        this.visibility = visibility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_an_yesno.yesno_answer
     *
     * @return the value of t_an_yesno.yesno_answer
     *
     * @mbggenerated
     */
    public String getYesnoAnswer() {
        return yesnoAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_an_yesno.yesno_answer
     *
     * @param yesnoAnswer the value for t_an_yesno.yesno_answer
     *
     * @mbggenerated
     */
    public void setYesnoAnswer(String yesnoAnswer) {
        this.yesnoAnswer = yesnoAnswer;
    }
}