package com.key.dwsurvey.pojo;

import java.io.Serializable;
import java.util.Date;

public class ImportError implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_import_error.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_import_error.cell1value
     *
     * @mbggenerated
     */
    private String cell1value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_import_error.cell2value
     *
     * @mbggenerated
     */
    private String cell2value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_import_error.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_import_error.db_id
     *
     * @mbggenerated
     */
    private String dbId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_import_error.file_name
     *
     * @mbggenerated
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_import_error.row_index
     *
     * @mbggenerated
     */
    private Integer rowIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_import_error.table_name
     *
     * @mbggenerated
     */
    private String tableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_import_error.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_import_error
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_import_error.id
     *
     * @return the value of t_import_error.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_import_error.id
     *
     * @param id the value for t_import_error.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_import_error.cell1value
     *
     * @return the value of t_import_error.cell1value
     *
     * @mbggenerated
     */
    public String getCell1value() {
        return cell1value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_import_error.cell1value
     *
     * @param cell1value the value for t_import_error.cell1value
     *
     * @mbggenerated
     */
    public void setCell1value(String cell1value) {
        this.cell1value = cell1value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_import_error.cell2value
     *
     * @return the value of t_import_error.cell2value
     *
     * @mbggenerated
     */
    public String getCell2value() {
        return cell2value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_import_error.cell2value
     *
     * @param cell2value the value for t_import_error.cell2value
     *
     * @mbggenerated
     */
    public void setCell2value(String cell2value) {
        this.cell2value = cell2value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_import_error.create_date
     *
     * @return the value of t_import_error.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_import_error.create_date
     *
     * @param createDate the value for t_import_error.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_import_error.db_id
     *
     * @return the value of t_import_error.db_id
     *
     * @mbggenerated
     */
    public String getDbId() {
        return dbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_import_error.db_id
     *
     * @param dbId the value for t_import_error.db_id
     *
     * @mbggenerated
     */
    public void setDbId(String dbId) {
        this.dbId = dbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_import_error.file_name
     *
     * @return the value of t_import_error.file_name
     *
     * @mbggenerated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_import_error.file_name
     *
     * @param fileName the value for t_import_error.file_name
     *
     * @mbggenerated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_import_error.row_index
     *
     * @return the value of t_import_error.row_index
     *
     * @mbggenerated
     */
    public Integer getRowIndex() {
        return rowIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_import_error.row_index
     *
     * @param rowIndex the value for t_import_error.row_index
     *
     * @mbggenerated
     */
    public void setRowIndex(Integer rowIndex) {
        this.rowIndex = rowIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_import_error.table_name
     *
     * @return the value of t_import_error.table_name
     *
     * @mbggenerated
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_import_error.table_name
     *
     * @param tableName the value for t_import_error.table_name
     *
     * @mbggenerated
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_import_error.user_id
     *
     * @return the value of t_import_error.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_import_error.user_id
     *
     * @param userId the value for t_import_error.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }
}