package com.key.dwsurvey.pojo;

import java.io.Serializable;

public class MailInviteInbox implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail_invite_inbox.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail_invite_inbox.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail_invite_inbox.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail_invite_inbox.sendcloud_id
     *
     * @mbggenerated
     */
    private String sendcloudId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail_invite_inbox.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail_invite_inbox.survey_mail_invite_id
     *
     * @mbggenerated
     */
    private String surveyMailInviteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail_invite_inbox.us_contacts_id
     *
     * @mbggenerated
     */
    private String usContactsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail_invite_inbox.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_mail_invite_inbox
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail_invite_inbox.id
     *
     * @return the value of t_mail_invite_inbox.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail_invite_inbox.id
     *
     * @param id the value for t_mail_invite_inbox.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail_invite_inbox.email
     *
     * @return the value of t_mail_invite_inbox.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail_invite_inbox.email
     *
     * @param email the value for t_mail_invite_inbox.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail_invite_inbox.name
     *
     * @return the value of t_mail_invite_inbox.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail_invite_inbox.name
     *
     * @param name the value for t_mail_invite_inbox.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail_invite_inbox.sendcloud_id
     *
     * @return the value of t_mail_invite_inbox.sendcloud_id
     *
     * @mbggenerated
     */
    public String getSendcloudId() {
        return sendcloudId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail_invite_inbox.sendcloud_id
     *
     * @param sendcloudId the value for t_mail_invite_inbox.sendcloud_id
     *
     * @mbggenerated
     */
    public void setSendcloudId(String sendcloudId) {
        this.sendcloudId = sendcloudId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail_invite_inbox.status
     *
     * @return the value of t_mail_invite_inbox.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail_invite_inbox.status
     *
     * @param status the value for t_mail_invite_inbox.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail_invite_inbox.survey_mail_invite_id
     *
     * @return the value of t_mail_invite_inbox.survey_mail_invite_id
     *
     * @mbggenerated
     */
    public String getSurveyMailInviteId() {
        return surveyMailInviteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail_invite_inbox.survey_mail_invite_id
     *
     * @param surveyMailInviteId the value for t_mail_invite_inbox.survey_mail_invite_id
     *
     * @mbggenerated
     */
    public void setSurveyMailInviteId(String surveyMailInviteId) {
        this.surveyMailInviteId = surveyMailInviteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail_invite_inbox.us_contacts_id
     *
     * @return the value of t_mail_invite_inbox.us_contacts_id
     *
     * @mbggenerated
     */
    public String getUsContactsId() {
        return usContactsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail_invite_inbox.us_contacts_id
     *
     * @param usContactsId the value for t_mail_invite_inbox.us_contacts_id
     *
     * @mbggenerated
     */
    public void setUsContactsId(String usContactsId) {
        this.usContactsId = usContactsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail_invite_inbox.user_id
     *
     * @return the value of t_mail_invite_inbox.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail_invite_inbox.user_id
     *
     * @param userId the value for t_mail_invite_inbox.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }
}