package com.key.dwsurvey.pojo;

import java.io.Serializable;
import java.util.Date;

public class QuestionLogic implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_logic.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_logic.cg_qu_item_id
     *
     * @mbggenerated
     */
    private String cgQuItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_logic.ck_qu_id
     *
     * @mbggenerated
     */
    private String ckQuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_logic.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_logic.ge_le
     *
     * @mbggenerated
     */
    private String geLe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_logic.logic_type
     *
     * @mbggenerated
     */
    private String logicType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_logic.score_num
     *
     * @mbggenerated
     */
    private Integer scoreNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_logic.sk_qu_id
     *
     * @mbggenerated
     */
    private String skQuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_logic.visibility
     *
     * @mbggenerated
     */
    private Integer visibility;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_question_logic
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_logic.id
     *
     * @return the value of t_question_logic.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_logic.id
     *
     * @param id the value for t_question_logic.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_logic.cg_qu_item_id
     *
     * @return the value of t_question_logic.cg_qu_item_id
     *
     * @mbggenerated
     */
    public String getCgQuItemId() {
        return cgQuItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_logic.cg_qu_item_id
     *
     * @param cgQuItemId the value for t_question_logic.cg_qu_item_id
     *
     * @mbggenerated
     */
    public void setCgQuItemId(String cgQuItemId) {
        this.cgQuItemId = cgQuItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_logic.ck_qu_id
     *
     * @return the value of t_question_logic.ck_qu_id
     *
     * @mbggenerated
     */
    public String getCkQuId() {
        return ckQuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_logic.ck_qu_id
     *
     * @param ckQuId the value for t_question_logic.ck_qu_id
     *
     * @mbggenerated
     */
    public void setCkQuId(String ckQuId) {
        this.ckQuId = ckQuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_logic.create_date
     *
     * @return the value of t_question_logic.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_logic.create_date
     *
     * @param createDate the value for t_question_logic.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_logic.ge_le
     *
     * @return the value of t_question_logic.ge_le
     *
     * @mbggenerated
     */
    public String getGeLe() {
        return geLe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_logic.ge_le
     *
     * @param geLe the value for t_question_logic.ge_le
     *
     * @mbggenerated
     */
    public void setGeLe(String geLe) {
        this.geLe = geLe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_logic.logic_type
     *
     * @return the value of t_question_logic.logic_type
     *
     * @mbggenerated
     */
    public String getLogicType() {
        return logicType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_logic.logic_type
     *
     * @param logicType the value for t_question_logic.logic_type
     *
     * @mbggenerated
     */
    public void setLogicType(String logicType) {
        this.logicType = logicType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_logic.score_num
     *
     * @return the value of t_question_logic.score_num
     *
     * @mbggenerated
     */
    public Integer getScoreNum() {
        return scoreNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_logic.score_num
     *
     * @param scoreNum the value for t_question_logic.score_num
     *
     * @mbggenerated
     */
    public void setScoreNum(Integer scoreNum) {
        this.scoreNum = scoreNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_logic.sk_qu_id
     *
     * @return the value of t_question_logic.sk_qu_id
     *
     * @mbggenerated
     */
    public String getSkQuId() {
        return skQuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_logic.sk_qu_id
     *
     * @param skQuId the value for t_question_logic.sk_qu_id
     *
     * @mbggenerated
     */
    public void setSkQuId(String skQuId) {
        this.skQuId = skQuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_logic.visibility
     *
     * @return the value of t_question_logic.visibility
     *
     * @mbggenerated
     */
    public Integer getVisibility() {
        return visibility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_logic.visibility
     *
     * @param visibility the value for t_question_logic.visibility
     *
     * @mbggenerated
     */
    public void setVisibility(Integer visibility) {
        this.visibility = visibility;
    }
}