package com.key.dwsurvey.pojo;

import java.io.Serializable;
import java.util.Date;

public class QuestionBank implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_bank.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_bank.bank_name
     *
     * @mbggenerated
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_bank.bank_note
     *
     * @mbggenerated
     */
    private String bankNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_bank.bank_state
     *
     * @mbggenerated
     */
    private Integer bankState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_bank.bank_tag
     *
     * @mbggenerated
     */
    private Integer bankTag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_bank.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_bank.dir_type
     *
     * @mbggenerated
     */
    private Integer dirType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_bank.excerpt_num
     *
     * @mbggenerated
     */
    private Integer excerptNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_bank.group_id1
     *
     * @mbggenerated
     */
    private String groupId1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_bank.group_id2
     *
     * @mbggenerated
     */
    private String groupId2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_bank.parent_id
     *
     * @mbggenerated
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_bank.qu_num
     *
     * @mbggenerated
     */
    private Integer quNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_bank.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_bank.visibility
     *
     * @mbggenerated
     */
    private Integer visibility;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_question_bank
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_bank.id
     *
     * @return the value of t_question_bank.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_bank.id
     *
     * @param id the value for t_question_bank.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_bank.bank_name
     *
     * @return the value of t_question_bank.bank_name
     *
     * @mbggenerated
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_bank.bank_name
     *
     * @param bankName the value for t_question_bank.bank_name
     *
     * @mbggenerated
     */
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_bank.bank_note
     *
     * @return the value of t_question_bank.bank_note
     *
     * @mbggenerated
     */
    public String getBankNote() {
        return bankNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_bank.bank_note
     *
     * @param bankNote the value for t_question_bank.bank_note
     *
     * @mbggenerated
     */
    public void setBankNote(String bankNote) {
        this.bankNote = bankNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_bank.bank_state
     *
     * @return the value of t_question_bank.bank_state
     *
     * @mbggenerated
     */
    public Integer getBankState() {
        return bankState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_bank.bank_state
     *
     * @param bankState the value for t_question_bank.bank_state
     *
     * @mbggenerated
     */
    public void setBankState(Integer bankState) {
        this.bankState = bankState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_bank.bank_tag
     *
     * @return the value of t_question_bank.bank_tag
     *
     * @mbggenerated
     */
    public Integer getBankTag() {
        return bankTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_bank.bank_tag
     *
     * @param bankTag the value for t_question_bank.bank_tag
     *
     * @mbggenerated
     */
    public void setBankTag(Integer bankTag) {
        this.bankTag = bankTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_bank.create_date
     *
     * @return the value of t_question_bank.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_bank.create_date
     *
     * @param createDate the value for t_question_bank.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_bank.dir_type
     *
     * @return the value of t_question_bank.dir_type
     *
     * @mbggenerated
     */
    public Integer getDirType() {
        return dirType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_bank.dir_type
     *
     * @param dirType the value for t_question_bank.dir_type
     *
     * @mbggenerated
     */
    public void setDirType(Integer dirType) {
        this.dirType = dirType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_bank.excerpt_num
     *
     * @return the value of t_question_bank.excerpt_num
     *
     * @mbggenerated
     */
    public Integer getExcerptNum() {
        return excerptNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_bank.excerpt_num
     *
     * @param excerptNum the value for t_question_bank.excerpt_num
     *
     * @mbggenerated
     */
    public void setExcerptNum(Integer excerptNum) {
        this.excerptNum = excerptNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_bank.group_id1
     *
     * @return the value of t_question_bank.group_id1
     *
     * @mbggenerated
     */
    public String getGroupId1() {
        return groupId1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_bank.group_id1
     *
     * @param groupId1 the value for t_question_bank.group_id1
     *
     * @mbggenerated
     */
    public void setGroupId1(String groupId1) {
        this.groupId1 = groupId1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_bank.group_id2
     *
     * @return the value of t_question_bank.group_id2
     *
     * @mbggenerated
     */
    public String getGroupId2() {
        return groupId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_bank.group_id2
     *
     * @param groupId2 the value for t_question_bank.group_id2
     *
     * @mbggenerated
     */
    public void setGroupId2(String groupId2) {
        this.groupId2 = groupId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_bank.parent_id
     *
     * @return the value of t_question_bank.parent_id
     *
     * @mbggenerated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_bank.parent_id
     *
     * @param parentId the value for t_question_bank.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_bank.qu_num
     *
     * @return the value of t_question_bank.qu_num
     *
     * @mbggenerated
     */
    public Integer getQuNum() {
        return quNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_bank.qu_num
     *
     * @param quNum the value for t_question_bank.qu_num
     *
     * @mbggenerated
     */
    public void setQuNum(Integer quNum) {
        this.quNum = quNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_bank.user_id
     *
     * @return the value of t_question_bank.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_bank.user_id
     *
     * @param userId the value for t_question_bank.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_bank.visibility
     *
     * @return the value of t_question_bank.visibility
     *
     * @mbggenerated
     */
    public Integer getVisibility() {
        return visibility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_bank.visibility
     *
     * @param visibility the value for t_question_bank.visibility
     *
     * @mbggenerated
     */
    public void setVisibility(Integer visibility) {
        this.visibility = visibility;
    }
}