package com.key.dwsurvey.pojo;

import java.io.Serializable;
import java.util.Date;

public class Question implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.answer_input_row
     *
     * @mbggenerated
     */
    private Integer answerInputRow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.answer_input_width
     *
     * @mbggenerated
     */
    private Integer answerInputWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.belong_id
     *
     * @mbggenerated
     */
    private String belongId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.cell_count
     *
     * @mbggenerated
     */
    private Integer cellCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.check_type
     *
     * @mbggenerated
     */
    private Integer checkType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.contacts_attr
     *
     * @mbggenerated
     */
    private Integer contactsAttr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.contacts_field
     *
     * @mbggenerated
     */
    private String contactsField;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.copy_from_id
     *
     * @mbggenerated
     */
    private String copyFromId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.hv
     *
     * @mbggenerated
     */
    private Integer hv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.is_required
     *
     * @mbggenerated
     */
    private Integer isRequired;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.keywords
     *
     * @mbggenerated
     */
    private String keywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.order_by_id
     *
     * @mbggenerated
     */
    private Integer orderById;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.param_int01
     *
     * @mbggenerated
     */
    private Integer paramInt01;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.param_int02
     *
     * @mbggenerated
     */
    private Integer paramInt02;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.parent_qu_id
     *
     * @mbggenerated
     */
    private String parentQuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.qu_name
     *
     * @mbggenerated
     */
    private String quName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.qu_tag
     *
     * @mbggenerated
     */
    private Integer quTag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.qu_type
     *
     * @mbggenerated
     */
    private Integer quType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.rand_order
     *
     * @mbggenerated
     */
    private Integer randOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.tag
     *
     * @mbggenerated
     */
    private Integer tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.visibility
     *
     * @mbggenerated
     */
    private Integer visibility;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.yesno_option
     *
     * @mbggenerated
     */
    private Integer yesnoOption;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.qu_note
     *
     * @mbggenerated
     */
    private String quNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.qu_title
     *
     * @mbggenerated
     */
    private String quTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_question
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.id
     *
     * @return the value of t_question.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.id
     *
     * @param id the value for t_question.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.answer_input_row
     *
     * @return the value of t_question.answer_input_row
     *
     * @mbggenerated
     */
    public Integer getAnswerInputRow() {
        return answerInputRow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.answer_input_row
     *
     * @param answerInputRow the value for t_question.answer_input_row
     *
     * @mbggenerated
     */
    public void setAnswerInputRow(Integer answerInputRow) {
        this.answerInputRow = answerInputRow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.answer_input_width
     *
     * @return the value of t_question.answer_input_width
     *
     * @mbggenerated
     */
    public Integer getAnswerInputWidth() {
        return answerInputWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.answer_input_width
     *
     * @param answerInputWidth the value for t_question.answer_input_width
     *
     * @mbggenerated
     */
    public void setAnswerInputWidth(Integer answerInputWidth) {
        this.answerInputWidth = answerInputWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.belong_id
     *
     * @return the value of t_question.belong_id
     *
     * @mbggenerated
     */
    public String getBelongId() {
        return belongId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.belong_id
     *
     * @param belongId the value for t_question.belong_id
     *
     * @mbggenerated
     */
    public void setBelongId(String belongId) {
        this.belongId = belongId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.cell_count
     *
     * @return the value of t_question.cell_count
     *
     * @mbggenerated
     */
    public Integer getCellCount() {
        return cellCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.cell_count
     *
     * @param cellCount the value for t_question.cell_count
     *
     * @mbggenerated
     */
    public void setCellCount(Integer cellCount) {
        this.cellCount = cellCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.check_type
     *
     * @return the value of t_question.check_type
     *
     * @mbggenerated
     */
    public Integer getCheckType() {
        return checkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.check_type
     *
     * @param checkType the value for t_question.check_type
     *
     * @mbggenerated
     */
    public void setCheckType(Integer checkType) {
        this.checkType = checkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.contacts_attr
     *
     * @return the value of t_question.contacts_attr
     *
     * @mbggenerated
     */
    public Integer getContactsAttr() {
        return contactsAttr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.contacts_attr
     *
     * @param contactsAttr the value for t_question.contacts_attr
     *
     * @mbggenerated
     */
    public void setContactsAttr(Integer contactsAttr) {
        this.contactsAttr = contactsAttr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.contacts_field
     *
     * @return the value of t_question.contacts_field
     *
     * @mbggenerated
     */
    public String getContactsField() {
        return contactsField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.contacts_field
     *
     * @param contactsField the value for t_question.contacts_field
     *
     * @mbggenerated
     */
    public void setContactsField(String contactsField) {
        this.contactsField = contactsField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.copy_from_id
     *
     * @return the value of t_question.copy_from_id
     *
     * @mbggenerated
     */
    public String getCopyFromId() {
        return copyFromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.copy_from_id
     *
     * @param copyFromId the value for t_question.copy_from_id
     *
     * @mbggenerated
     */
    public void setCopyFromId(String copyFromId) {
        this.copyFromId = copyFromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.create_date
     *
     * @return the value of t_question.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.create_date
     *
     * @param createDate the value for t_question.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.hv
     *
     * @return the value of t_question.hv
     *
     * @mbggenerated
     */
    public Integer getHv() {
        return hv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.hv
     *
     * @param hv the value for t_question.hv
     *
     * @mbggenerated
     */
    public void setHv(Integer hv) {
        this.hv = hv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.is_required
     *
     * @return the value of t_question.is_required
     *
     * @mbggenerated
     */
    public Integer getIsRequired() {
        return isRequired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.is_required
     *
     * @param isRequired the value for t_question.is_required
     *
     * @mbggenerated
     */
    public void setIsRequired(Integer isRequired) {
        this.isRequired = isRequired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.keywords
     *
     * @return the value of t_question.keywords
     *
     * @mbggenerated
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.keywords
     *
     * @param keywords the value for t_question.keywords
     *
     * @mbggenerated
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.order_by_id
     *
     * @return the value of t_question.order_by_id
     *
     * @mbggenerated
     */
    public Integer getOrderById() {
        return orderById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.order_by_id
     *
     * @param orderById the value for t_question.order_by_id
     *
     * @mbggenerated
     */
    public void setOrderById(Integer orderById) {
        this.orderById = orderById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.param_int01
     *
     * @return the value of t_question.param_int01
     *
     * @mbggenerated
     */
    public Integer getParamInt01() {
        return paramInt01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.param_int01
     *
     * @param paramInt01 the value for t_question.param_int01
     *
     * @mbggenerated
     */
    public void setParamInt01(Integer paramInt01) {
        this.paramInt01 = paramInt01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.param_int02
     *
     * @return the value of t_question.param_int02
     *
     * @mbggenerated
     */
    public Integer getParamInt02() {
        return paramInt02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.param_int02
     *
     * @param paramInt02 the value for t_question.param_int02
     *
     * @mbggenerated
     */
    public void setParamInt02(Integer paramInt02) {
        this.paramInt02 = paramInt02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.parent_qu_id
     *
     * @return the value of t_question.parent_qu_id
     *
     * @mbggenerated
     */
    public String getParentQuId() {
        return parentQuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.parent_qu_id
     *
     * @param parentQuId the value for t_question.parent_qu_id
     *
     * @mbggenerated
     */
    public void setParentQuId(String parentQuId) {
        this.parentQuId = parentQuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.qu_name
     *
     * @return the value of t_question.qu_name
     *
     * @mbggenerated
     */
    public String getQuName() {
        return quName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.qu_name
     *
     * @param quName the value for t_question.qu_name
     *
     * @mbggenerated
     */
    public void setQuName(String quName) {
        this.quName = quName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.qu_tag
     *
     * @return the value of t_question.qu_tag
     *
     * @mbggenerated
     */
    public Integer getQuTag() {
        return quTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.qu_tag
     *
     * @param quTag the value for t_question.qu_tag
     *
     * @mbggenerated
     */
    public void setQuTag(Integer quTag) {
        this.quTag = quTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.qu_type
     *
     * @return the value of t_question.qu_type
     *
     * @mbggenerated
     */
    public Integer getQuType() {
        return quType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.qu_type
     *
     * @param quType the value for t_question.qu_type
     *
     * @mbggenerated
     */
    public void setQuType(Integer quType) {
        this.quType = quType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.rand_order
     *
     * @return the value of t_question.rand_order
     *
     * @mbggenerated
     */
    public Integer getRandOrder() {
        return randOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.rand_order
     *
     * @param randOrder the value for t_question.rand_order
     *
     * @mbggenerated
     */
    public void setRandOrder(Integer randOrder) {
        this.randOrder = randOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.tag
     *
     * @return the value of t_question.tag
     *
     * @mbggenerated
     */
    public Integer getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.tag
     *
     * @param tag the value for t_question.tag
     *
     * @mbggenerated
     */
    public void setTag(Integer tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.visibility
     *
     * @return the value of t_question.visibility
     *
     * @mbggenerated
     */
    public Integer getVisibility() {
        return visibility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.visibility
     *
     * @param visibility the value for t_question.visibility
     *
     * @mbggenerated
     */
    public void setVisibility(Integer visibility) {
        this.visibility = visibility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.yesno_option
     *
     * @return the value of t_question.yesno_option
     *
     * @mbggenerated
     */
    public Integer getYesnoOption() {
        return yesnoOption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.yesno_option
     *
     * @param yesnoOption the value for t_question.yesno_option
     *
     * @mbggenerated
     */
    public void setYesnoOption(Integer yesnoOption) {
        this.yesnoOption = yesnoOption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.qu_note
     *
     * @return the value of t_question.qu_note
     *
     * @mbggenerated
     */
    public String getQuNote() {
        return quNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.qu_note
     *
     * @param quNote the value for t_question.qu_note
     *
     * @mbggenerated
     */
    public void setQuNote(String quNote) {
        this.quNote = quNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.qu_title
     *
     * @return the value of t_question.qu_title
     *
     * @mbggenerated
     */
    public String getQuTitle() {
        return quTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.qu_title
     *
     * @param quTitle the value for t_question.qu_title
     *
     * @mbggenerated
     */
    public void setQuTitle(String quTitle) {
        this.quTitle = quTitle;
    }
}