package com.key.dwsurvey.pojo;

import java.io.Serializable;

public class QuRadio implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qu_radio.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qu_radio.check_type
     *
     * @mbggenerated
     */
    private Integer checkType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qu_radio.is_note
     *
     * @mbggenerated
     */
    private Integer isNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qu_radio.is_required_fill
     *
     * @mbggenerated
     */
    private Integer isRequiredFill;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qu_radio.option_name
     *
     * @mbggenerated
     */
    private String optionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qu_radio.option_title
     *
     * @mbggenerated
     */
    private String optionTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qu_radio.order_by_id
     *
     * @mbggenerated
     */
    private Integer orderById;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qu_radio.qu_id
     *
     * @mbggenerated
     */
    private String quId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qu_radio.visibility
     *
     * @mbggenerated
     */
    private Integer visibility;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_qu_radio
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qu_radio.id
     *
     * @return the value of t_qu_radio.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qu_radio.id
     *
     * @param id the value for t_qu_radio.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qu_radio.check_type
     *
     * @return the value of t_qu_radio.check_type
     *
     * @mbggenerated
     */
    public Integer getCheckType() {
        return checkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qu_radio.check_type
     *
     * @param checkType the value for t_qu_radio.check_type
     *
     * @mbggenerated
     */
    public void setCheckType(Integer checkType) {
        this.checkType = checkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qu_radio.is_note
     *
     * @return the value of t_qu_radio.is_note
     *
     * @mbggenerated
     */
    public Integer getIsNote() {
        return isNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qu_radio.is_note
     *
     * @param isNote the value for t_qu_radio.is_note
     *
     * @mbggenerated
     */
    public void setIsNote(Integer isNote) {
        this.isNote = isNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qu_radio.is_required_fill
     *
     * @return the value of t_qu_radio.is_required_fill
     *
     * @mbggenerated
     */
    public Integer getIsRequiredFill() {
        return isRequiredFill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qu_radio.is_required_fill
     *
     * @param isRequiredFill the value for t_qu_radio.is_required_fill
     *
     * @mbggenerated
     */
    public void setIsRequiredFill(Integer isRequiredFill) {
        this.isRequiredFill = isRequiredFill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qu_radio.option_name
     *
     * @return the value of t_qu_radio.option_name
     *
     * @mbggenerated
     */
    public String getOptionName() {
        return optionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qu_radio.option_name
     *
     * @param optionName the value for t_qu_radio.option_name
     *
     * @mbggenerated
     */
    public void setOptionName(String optionName) {
        this.optionName = optionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qu_radio.option_title
     *
     * @return the value of t_qu_radio.option_title
     *
     * @mbggenerated
     */
    public String getOptionTitle() {
        return optionTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qu_radio.option_title
     *
     * @param optionTitle the value for t_qu_radio.option_title
     *
     * @mbggenerated
     */
    public void setOptionTitle(String optionTitle) {
        this.optionTitle = optionTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qu_radio.order_by_id
     *
     * @return the value of t_qu_radio.order_by_id
     *
     * @mbggenerated
     */
    public Integer getOrderById() {
        return orderById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qu_radio.order_by_id
     *
     * @param orderById the value for t_qu_radio.order_by_id
     *
     * @mbggenerated
     */
    public void setOrderById(Integer orderById) {
        this.orderById = orderById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qu_radio.qu_id
     *
     * @return the value of t_qu_radio.qu_id
     *
     * @mbggenerated
     */
    public String getQuId() {
        return quId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qu_radio.qu_id
     *
     * @param quId the value for t_qu_radio.qu_id
     *
     * @mbggenerated
     */
    public void setQuId(String quId) {
        this.quId = quId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qu_radio.visibility
     *
     * @return the value of t_qu_radio.visibility
     *
     * @mbggenerated
     */
    public Integer getVisibility() {
        return visibility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qu_radio.visibility
     *
     * @param visibility the value for t_qu_radio.visibility
     *
     * @mbggenerated
     */
    public void setVisibility(Integer visibility) {
        this.visibility = visibility;
    }
}