package com.key.dwsurvey.pojo;

import java.io.Serializable;
import java.util.Date;

public class SurveyAnswer implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_answer.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_answer.addr
     *
     * @mbggenerated
     */
    private String addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_answer.bg_an_date
     *
     * @mbggenerated
     */
    private Date bgAnDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_answer.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_answer.complete_item_num
     *
     * @mbggenerated
     */
    private Integer completeItemNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_answer.complete_num
     *
     * @mbggenerated
     */
    private Integer completeNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_answer.data_source
     *
     * @mbggenerated
     */
    private Integer dataSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_answer.end_an_date
     *
     * @mbggenerated
     */
    private Date endAnDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_answer.handle_state
     *
     * @mbggenerated
     */
    private Integer handleState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_answer.ip_addr
     *
     * @mbggenerated
     */
    private String ipAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_answer.is_complete
     *
     * @mbggenerated
     */
    private Integer isComplete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_answer.is_effective
     *
     * @mbggenerated
     */
    private Integer isEffective;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_answer.pc_mac
     *
     * @mbggenerated
     */
    private String pcMac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_answer.qu_num
     *
     * @mbggenerated
     */
    private Integer quNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_answer.survey_id
     *
     * @mbggenerated
     */
    private String surveyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_answer.total_time
     *
     * @mbggenerated
     */
    private Float totalTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_answer.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_survey_answer
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_answer.id
     *
     * @return the value of t_survey_answer.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_answer.id
     *
     * @param id the value for t_survey_answer.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_answer.addr
     *
     * @return the value of t_survey_answer.addr
     *
     * @mbggenerated
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_answer.addr
     *
     * @param addr the value for t_survey_answer.addr
     *
     * @mbggenerated
     */
    public void setAddr(String addr) {
        this.addr = addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_answer.bg_an_date
     *
     * @return the value of t_survey_answer.bg_an_date
     *
     * @mbggenerated
     */
    public Date getBgAnDate() {
        return bgAnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_answer.bg_an_date
     *
     * @param bgAnDate the value for t_survey_answer.bg_an_date
     *
     * @mbggenerated
     */
    public void setBgAnDate(Date bgAnDate) {
        this.bgAnDate = bgAnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_answer.city
     *
     * @return the value of t_survey_answer.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_answer.city
     *
     * @param city the value for t_survey_answer.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_answer.complete_item_num
     *
     * @return the value of t_survey_answer.complete_item_num
     *
     * @mbggenerated
     */
    public Integer getCompleteItemNum() {
        return completeItemNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_answer.complete_item_num
     *
     * @param completeItemNum the value for t_survey_answer.complete_item_num
     *
     * @mbggenerated
     */
    public void setCompleteItemNum(Integer completeItemNum) {
        this.completeItemNum = completeItemNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_answer.complete_num
     *
     * @return the value of t_survey_answer.complete_num
     *
     * @mbggenerated
     */
    public Integer getCompleteNum() {
        return completeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_answer.complete_num
     *
     * @param completeNum the value for t_survey_answer.complete_num
     *
     * @mbggenerated
     */
    public void setCompleteNum(Integer completeNum) {
        this.completeNum = completeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_answer.data_source
     *
     * @return the value of t_survey_answer.data_source
     *
     * @mbggenerated
     */
    public Integer getDataSource() {
        return dataSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_answer.data_source
     *
     * @param dataSource the value for t_survey_answer.data_source
     *
     * @mbggenerated
     */
    public void setDataSource(Integer dataSource) {
        this.dataSource = dataSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_answer.end_an_date
     *
     * @return the value of t_survey_answer.end_an_date
     *
     * @mbggenerated
     */
    public Date getEndAnDate() {
        return endAnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_answer.end_an_date
     *
     * @param endAnDate the value for t_survey_answer.end_an_date
     *
     * @mbggenerated
     */
    public void setEndAnDate(Date endAnDate) {
        this.endAnDate = endAnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_answer.handle_state
     *
     * @return the value of t_survey_answer.handle_state
     *
     * @mbggenerated
     */
    public Integer getHandleState() {
        return handleState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_answer.handle_state
     *
     * @param handleState the value for t_survey_answer.handle_state
     *
     * @mbggenerated
     */
    public void setHandleState(Integer handleState) {
        this.handleState = handleState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_answer.ip_addr
     *
     * @return the value of t_survey_answer.ip_addr
     *
     * @mbggenerated
     */
    public String getIpAddr() {
        return ipAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_answer.ip_addr
     *
     * @param ipAddr the value for t_survey_answer.ip_addr
     *
     * @mbggenerated
     */
    public void setIpAddr(String ipAddr) {
        this.ipAddr = ipAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_answer.is_complete
     *
     * @return the value of t_survey_answer.is_complete
     *
     * @mbggenerated
     */
    public Integer getIsComplete() {
        return isComplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_answer.is_complete
     *
     * @param isComplete the value for t_survey_answer.is_complete
     *
     * @mbggenerated
     */
    public void setIsComplete(Integer isComplete) {
        this.isComplete = isComplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_answer.is_effective
     *
     * @return the value of t_survey_answer.is_effective
     *
     * @mbggenerated
     */
    public Integer getIsEffective() {
        return isEffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_answer.is_effective
     *
     * @param isEffective the value for t_survey_answer.is_effective
     *
     * @mbggenerated
     */
    public void setIsEffective(Integer isEffective) {
        this.isEffective = isEffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_answer.pc_mac
     *
     * @return the value of t_survey_answer.pc_mac
     *
     * @mbggenerated
     */
    public String getPcMac() {
        return pcMac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_answer.pc_mac
     *
     * @param pcMac the value for t_survey_answer.pc_mac
     *
     * @mbggenerated
     */
    public void setPcMac(String pcMac) {
        this.pcMac = pcMac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_answer.qu_num
     *
     * @return the value of t_survey_answer.qu_num
     *
     * @mbggenerated
     */
    public Integer getQuNum() {
        return quNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_answer.qu_num
     *
     * @param quNum the value for t_survey_answer.qu_num
     *
     * @mbggenerated
     */
    public void setQuNum(Integer quNum) {
        this.quNum = quNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_answer.survey_id
     *
     * @return the value of t_survey_answer.survey_id
     *
     * @mbggenerated
     */
    public String getSurveyId() {
        return surveyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_answer.survey_id
     *
     * @param surveyId the value for t_survey_answer.survey_id
     *
     * @mbggenerated
     */
    public void setSurveyId(String surveyId) {
        this.surveyId = surveyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_answer.total_time
     *
     * @return the value of t_survey_answer.total_time
     *
     * @mbggenerated
     */
    public Float getTotalTime() {
        return totalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_answer.total_time
     *
     * @param totalTime the value for t_survey_answer.total_time
     *
     * @mbggenerated
     */
    public void setTotalTime(Float totalTime) {
        this.totalTime = totalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_answer.user_id
     *
     * @return the value of t_survey_answer.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_answer.user_id
     *
     * @param userId the value for t_survey_answer.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }
}