package com.key.dwsurvey.pojo;

import java.io.Serializable;

public class SurveyStyle implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.body_bg_color
     *
     * @mbggenerated
     */
    private String bodyBgColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.body_bg_image
     *
     * @mbggenerated
     */
    private String bodyBgImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.show_survey_haed
     *
     * @mbggenerated
     */
    private Integer showSurveyHaed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.survey_bg_color
     *
     * @mbggenerated
     */
    private String surveyBgColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.survey_bg_image
     *
     * @mbggenerated
     */
    private String surveyBgImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.survey_content_bg_colo_topr
     *
     * @mbggenerated
     */
    private String surveyContentBgColoTopr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.survey_content_bg_color_bottom
     *
     * @mbggenerated
     */
    private String surveyContentBgColorBottom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.survey_content_bg_color_middle
     *
     * @mbggenerated
     */
    private String surveyContentBgColorMiddle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.survey_content_bg_image_bottom
     *
     * @mbggenerated
     */
    private String surveyContentBgImageBottom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.survey_content_bg_image_middle
     *
     * @mbggenerated
     */
    private String surveyContentBgImageMiddle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.survey_content_bg_image_top
     *
     * @mbggenerated
     */
    private String surveyContentBgImageTop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.survey_content_padding_bottom
     *
     * @mbggenerated
     */
    private Integer surveyContentPaddingBottom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.survey_content_padding_left
     *
     * @mbggenerated
     */
    private Integer surveyContentPaddingLeft;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.survey_content_padding_right
     *
     * @mbggenerated
     */
    private Integer surveyContentPaddingRight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.survey_content_padding_top
     *
     * @mbggenerated
     */
    private Integer surveyContentPaddingTop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.survey_content_width
     *
     * @mbggenerated
     */
    private Integer surveyContentWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.survey_head_bg_color
     *
     * @mbggenerated
     */
    private String surveyHeadBgColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.survey_head_bg_image
     *
     * @mbggenerated
     */
    private String surveyHeadBgImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.survey_head_height
     *
     * @mbggenerated
     */
    private Integer surveyHeadHeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.survey_head_padding_bottom
     *
     * @mbggenerated
     */
    private Integer surveyHeadPaddingBottom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.survey_head_padding_left
     *
     * @mbggenerated
     */
    private Integer surveyHeadPaddingLeft;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.survey_head_padding_right
     *
     * @mbggenerated
     */
    private Integer surveyHeadPaddingRight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.survey_head_padding_top
     *
     * @mbggenerated
     */
    private Integer surveyHeadPaddingTop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.survey_head_width
     *
     * @mbggenerated
     */
    private Integer surveyHeadWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.survey_id
     *
     * @mbggenerated
     */
    private String surveyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.survey_padding_bottom
     *
     * @mbggenerated
     */
    private String surveyPaddingBottom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.survey_padding_left
     *
     * @mbggenerated
     */
    private String surveyPaddingLeft;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.survey_padding_right
     *
     * @mbggenerated
     */
    private String surveyPaddingRight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.survey_padding_top
     *
     * @mbggenerated
     */
    private String surveyPaddingTop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.survey_style_type
     *
     * @mbggenerated
     */
    private Integer surveyStyleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.survey_width
     *
     * @mbggenerated
     */
    private Integer surveyWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.show_body_bi
     *
     * @mbggenerated
     */
    private Integer showBodyBi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.show_survey_bi
     *
     * @mbggenerated
     */
    private Integer showSurveyBi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.show_survey_cbim
     *
     * @mbggenerated
     */
    private Integer showSurveyCbim;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.show_survey_hbgi
     *
     * @mbggenerated
     */
    private Integer showSurveyHbgi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.survey_content_bg_color_top
     *
     * @mbggenerated
     */
    private String surveyContentBgColorTop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.show_survey_logo
     *
     * @mbggenerated
     */
    private Integer showSurveyLogo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.survey_logo_image
     *
     * @mbggenerated
     */
    private String surveyLogoImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.question_option_text_color
     *
     * @mbggenerated
     */
    private String questionOptionTextColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.question_title_text_color
     *
     * @mbggenerated
     */
    private String questionTitleTextColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.survey_note_text_color
     *
     * @mbggenerated
     */
    private String surveyNoteTextColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.survey_title_text_color
     *
     * @mbggenerated
     */
    private String surveyTitleTextColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.survey_btn_bg_color
     *
     * @mbggenerated
     */
    private String surveyBtnBgColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.show_sur_note
     *
     * @mbggenerated
     */
    private Integer showSurNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.show_sur_title
     *
     * @mbggenerated
     */
    private Integer showSurTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.show_progressbar
     *
     * @mbggenerated
     */
    private Integer showProgressbar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_style.show_ti_num
     *
     * @mbggenerated
     */
    private Integer showTiNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_survey_style
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.id
     *
     * @return the value of t_survey_style.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.id
     *
     * @param id the value for t_survey_style.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.body_bg_color
     *
     * @return the value of t_survey_style.body_bg_color
     *
     * @mbggenerated
     */
    public String getBodyBgColor() {
        return bodyBgColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.body_bg_color
     *
     * @param bodyBgColor the value for t_survey_style.body_bg_color
     *
     * @mbggenerated
     */
    public void setBodyBgColor(String bodyBgColor) {
        this.bodyBgColor = bodyBgColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.body_bg_image
     *
     * @return the value of t_survey_style.body_bg_image
     *
     * @mbggenerated
     */
    public String getBodyBgImage() {
        return bodyBgImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.body_bg_image
     *
     * @param bodyBgImage the value for t_survey_style.body_bg_image
     *
     * @mbggenerated
     */
    public void setBodyBgImage(String bodyBgImage) {
        this.bodyBgImage = bodyBgImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.show_survey_haed
     *
     * @return the value of t_survey_style.show_survey_haed
     *
     * @mbggenerated
     */
    public Integer getShowSurveyHaed() {
        return showSurveyHaed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.show_survey_haed
     *
     * @param showSurveyHaed the value for t_survey_style.show_survey_haed
     *
     * @mbggenerated
     */
    public void setShowSurveyHaed(Integer showSurveyHaed) {
        this.showSurveyHaed = showSurveyHaed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.survey_bg_color
     *
     * @return the value of t_survey_style.survey_bg_color
     *
     * @mbggenerated
     */
    public String getSurveyBgColor() {
        return surveyBgColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.survey_bg_color
     *
     * @param surveyBgColor the value for t_survey_style.survey_bg_color
     *
     * @mbggenerated
     */
    public void setSurveyBgColor(String surveyBgColor) {
        this.surveyBgColor = surveyBgColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.survey_bg_image
     *
     * @return the value of t_survey_style.survey_bg_image
     *
     * @mbggenerated
     */
    public String getSurveyBgImage() {
        return surveyBgImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.survey_bg_image
     *
     * @param surveyBgImage the value for t_survey_style.survey_bg_image
     *
     * @mbggenerated
     */
    public void setSurveyBgImage(String surveyBgImage) {
        this.surveyBgImage = surveyBgImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.survey_content_bg_colo_topr
     *
     * @return the value of t_survey_style.survey_content_bg_colo_topr
     *
     * @mbggenerated
     */
    public String getSurveyContentBgColoTopr() {
        return surveyContentBgColoTopr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.survey_content_bg_colo_topr
     *
     * @param surveyContentBgColoTopr the value for t_survey_style.survey_content_bg_colo_topr
     *
     * @mbggenerated
     */
    public void setSurveyContentBgColoTopr(String surveyContentBgColoTopr) {
        this.surveyContentBgColoTopr = surveyContentBgColoTopr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.survey_content_bg_color_bottom
     *
     * @return the value of t_survey_style.survey_content_bg_color_bottom
     *
     * @mbggenerated
     */
    public String getSurveyContentBgColorBottom() {
        return surveyContentBgColorBottom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.survey_content_bg_color_bottom
     *
     * @param surveyContentBgColorBottom the value for t_survey_style.survey_content_bg_color_bottom
     *
     * @mbggenerated
     */
    public void setSurveyContentBgColorBottom(String surveyContentBgColorBottom) {
        this.surveyContentBgColorBottom = surveyContentBgColorBottom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.survey_content_bg_color_middle
     *
     * @return the value of t_survey_style.survey_content_bg_color_middle
     *
     * @mbggenerated
     */
    public String getSurveyContentBgColorMiddle() {
        return surveyContentBgColorMiddle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.survey_content_bg_color_middle
     *
     * @param surveyContentBgColorMiddle the value for t_survey_style.survey_content_bg_color_middle
     *
     * @mbggenerated
     */
    public void setSurveyContentBgColorMiddle(String surveyContentBgColorMiddle) {
        this.surveyContentBgColorMiddle = surveyContentBgColorMiddle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.survey_content_bg_image_bottom
     *
     * @return the value of t_survey_style.survey_content_bg_image_bottom
     *
     * @mbggenerated
     */
    public String getSurveyContentBgImageBottom() {
        return surveyContentBgImageBottom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.survey_content_bg_image_bottom
     *
     * @param surveyContentBgImageBottom the value for t_survey_style.survey_content_bg_image_bottom
     *
     * @mbggenerated
     */
    public void setSurveyContentBgImageBottom(String surveyContentBgImageBottom) {
        this.surveyContentBgImageBottom = surveyContentBgImageBottom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.survey_content_bg_image_middle
     *
     * @return the value of t_survey_style.survey_content_bg_image_middle
     *
     * @mbggenerated
     */
    public String getSurveyContentBgImageMiddle() {
        return surveyContentBgImageMiddle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.survey_content_bg_image_middle
     *
     * @param surveyContentBgImageMiddle the value for t_survey_style.survey_content_bg_image_middle
     *
     * @mbggenerated
     */
    public void setSurveyContentBgImageMiddle(String surveyContentBgImageMiddle) {
        this.surveyContentBgImageMiddle = surveyContentBgImageMiddle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.survey_content_bg_image_top
     *
     * @return the value of t_survey_style.survey_content_bg_image_top
     *
     * @mbggenerated
     */
    public String getSurveyContentBgImageTop() {
        return surveyContentBgImageTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.survey_content_bg_image_top
     *
     * @param surveyContentBgImageTop the value for t_survey_style.survey_content_bg_image_top
     *
     * @mbggenerated
     */
    public void setSurveyContentBgImageTop(String surveyContentBgImageTop) {
        this.surveyContentBgImageTop = surveyContentBgImageTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.survey_content_padding_bottom
     *
     * @return the value of t_survey_style.survey_content_padding_bottom
     *
     * @mbggenerated
     */
    public Integer getSurveyContentPaddingBottom() {
        return surveyContentPaddingBottom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.survey_content_padding_bottom
     *
     * @param surveyContentPaddingBottom the value for t_survey_style.survey_content_padding_bottom
     *
     * @mbggenerated
     */
    public void setSurveyContentPaddingBottom(Integer surveyContentPaddingBottom) {
        this.surveyContentPaddingBottom = surveyContentPaddingBottom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.survey_content_padding_left
     *
     * @return the value of t_survey_style.survey_content_padding_left
     *
     * @mbggenerated
     */
    public Integer getSurveyContentPaddingLeft() {
        return surveyContentPaddingLeft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.survey_content_padding_left
     *
     * @param surveyContentPaddingLeft the value for t_survey_style.survey_content_padding_left
     *
     * @mbggenerated
     */
    public void setSurveyContentPaddingLeft(Integer surveyContentPaddingLeft) {
        this.surveyContentPaddingLeft = surveyContentPaddingLeft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.survey_content_padding_right
     *
     * @return the value of t_survey_style.survey_content_padding_right
     *
     * @mbggenerated
     */
    public Integer getSurveyContentPaddingRight() {
        return surveyContentPaddingRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.survey_content_padding_right
     *
     * @param surveyContentPaddingRight the value for t_survey_style.survey_content_padding_right
     *
     * @mbggenerated
     */
    public void setSurveyContentPaddingRight(Integer surveyContentPaddingRight) {
        this.surveyContentPaddingRight = surveyContentPaddingRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.survey_content_padding_top
     *
     * @return the value of t_survey_style.survey_content_padding_top
     *
     * @mbggenerated
     */
    public Integer getSurveyContentPaddingTop() {
        return surveyContentPaddingTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.survey_content_padding_top
     *
     * @param surveyContentPaddingTop the value for t_survey_style.survey_content_padding_top
     *
     * @mbggenerated
     */
    public void setSurveyContentPaddingTop(Integer surveyContentPaddingTop) {
        this.surveyContentPaddingTop = surveyContentPaddingTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.survey_content_width
     *
     * @return the value of t_survey_style.survey_content_width
     *
     * @mbggenerated
     */
    public Integer getSurveyContentWidth() {
        return surveyContentWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.survey_content_width
     *
     * @param surveyContentWidth the value for t_survey_style.survey_content_width
     *
     * @mbggenerated
     */
    public void setSurveyContentWidth(Integer surveyContentWidth) {
        this.surveyContentWidth = surveyContentWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.survey_head_bg_color
     *
     * @return the value of t_survey_style.survey_head_bg_color
     *
     * @mbggenerated
     */
    public String getSurveyHeadBgColor() {
        return surveyHeadBgColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.survey_head_bg_color
     *
     * @param surveyHeadBgColor the value for t_survey_style.survey_head_bg_color
     *
     * @mbggenerated
     */
    public void setSurveyHeadBgColor(String surveyHeadBgColor) {
        this.surveyHeadBgColor = surveyHeadBgColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.survey_head_bg_image
     *
     * @return the value of t_survey_style.survey_head_bg_image
     *
     * @mbggenerated
     */
    public String getSurveyHeadBgImage() {
        return surveyHeadBgImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.survey_head_bg_image
     *
     * @param surveyHeadBgImage the value for t_survey_style.survey_head_bg_image
     *
     * @mbggenerated
     */
    public void setSurveyHeadBgImage(String surveyHeadBgImage) {
        this.surveyHeadBgImage = surveyHeadBgImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.survey_head_height
     *
     * @return the value of t_survey_style.survey_head_height
     *
     * @mbggenerated
     */
    public Integer getSurveyHeadHeight() {
        return surveyHeadHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.survey_head_height
     *
     * @param surveyHeadHeight the value for t_survey_style.survey_head_height
     *
     * @mbggenerated
     */
    public void setSurveyHeadHeight(Integer surveyHeadHeight) {
        this.surveyHeadHeight = surveyHeadHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.survey_head_padding_bottom
     *
     * @return the value of t_survey_style.survey_head_padding_bottom
     *
     * @mbggenerated
     */
    public Integer getSurveyHeadPaddingBottom() {
        return surveyHeadPaddingBottom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.survey_head_padding_bottom
     *
     * @param surveyHeadPaddingBottom the value for t_survey_style.survey_head_padding_bottom
     *
     * @mbggenerated
     */
    public void setSurveyHeadPaddingBottom(Integer surveyHeadPaddingBottom) {
        this.surveyHeadPaddingBottom = surveyHeadPaddingBottom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.survey_head_padding_left
     *
     * @return the value of t_survey_style.survey_head_padding_left
     *
     * @mbggenerated
     */
    public Integer getSurveyHeadPaddingLeft() {
        return surveyHeadPaddingLeft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.survey_head_padding_left
     *
     * @param surveyHeadPaddingLeft the value for t_survey_style.survey_head_padding_left
     *
     * @mbggenerated
     */
    public void setSurveyHeadPaddingLeft(Integer surveyHeadPaddingLeft) {
        this.surveyHeadPaddingLeft = surveyHeadPaddingLeft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.survey_head_padding_right
     *
     * @return the value of t_survey_style.survey_head_padding_right
     *
     * @mbggenerated
     */
    public Integer getSurveyHeadPaddingRight() {
        return surveyHeadPaddingRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.survey_head_padding_right
     *
     * @param surveyHeadPaddingRight the value for t_survey_style.survey_head_padding_right
     *
     * @mbggenerated
     */
    public void setSurveyHeadPaddingRight(Integer surveyHeadPaddingRight) {
        this.surveyHeadPaddingRight = surveyHeadPaddingRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.survey_head_padding_top
     *
     * @return the value of t_survey_style.survey_head_padding_top
     *
     * @mbggenerated
     */
    public Integer getSurveyHeadPaddingTop() {
        return surveyHeadPaddingTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.survey_head_padding_top
     *
     * @param surveyHeadPaddingTop the value for t_survey_style.survey_head_padding_top
     *
     * @mbggenerated
     */
    public void setSurveyHeadPaddingTop(Integer surveyHeadPaddingTop) {
        this.surveyHeadPaddingTop = surveyHeadPaddingTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.survey_head_width
     *
     * @return the value of t_survey_style.survey_head_width
     *
     * @mbggenerated
     */
    public Integer getSurveyHeadWidth() {
        return surveyHeadWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.survey_head_width
     *
     * @param surveyHeadWidth the value for t_survey_style.survey_head_width
     *
     * @mbggenerated
     */
    public void setSurveyHeadWidth(Integer surveyHeadWidth) {
        this.surveyHeadWidth = surveyHeadWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.survey_id
     *
     * @return the value of t_survey_style.survey_id
     *
     * @mbggenerated
     */
    public String getSurveyId() {
        return surveyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.survey_id
     *
     * @param surveyId the value for t_survey_style.survey_id
     *
     * @mbggenerated
     */
    public void setSurveyId(String surveyId) {
        this.surveyId = surveyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.survey_padding_bottom
     *
     * @return the value of t_survey_style.survey_padding_bottom
     *
     * @mbggenerated
     */
    public String getSurveyPaddingBottom() {
        return surveyPaddingBottom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.survey_padding_bottom
     *
     * @param surveyPaddingBottom the value for t_survey_style.survey_padding_bottom
     *
     * @mbggenerated
     */
    public void setSurveyPaddingBottom(String surveyPaddingBottom) {
        this.surveyPaddingBottom = surveyPaddingBottom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.survey_padding_left
     *
     * @return the value of t_survey_style.survey_padding_left
     *
     * @mbggenerated
     */
    public String getSurveyPaddingLeft() {
        return surveyPaddingLeft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.survey_padding_left
     *
     * @param surveyPaddingLeft the value for t_survey_style.survey_padding_left
     *
     * @mbggenerated
     */
    public void setSurveyPaddingLeft(String surveyPaddingLeft) {
        this.surveyPaddingLeft = surveyPaddingLeft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.survey_padding_right
     *
     * @return the value of t_survey_style.survey_padding_right
     *
     * @mbggenerated
     */
    public String getSurveyPaddingRight() {
        return surveyPaddingRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.survey_padding_right
     *
     * @param surveyPaddingRight the value for t_survey_style.survey_padding_right
     *
     * @mbggenerated
     */
    public void setSurveyPaddingRight(String surveyPaddingRight) {
        this.surveyPaddingRight = surveyPaddingRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.survey_padding_top
     *
     * @return the value of t_survey_style.survey_padding_top
     *
     * @mbggenerated
     */
    public String getSurveyPaddingTop() {
        return surveyPaddingTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.survey_padding_top
     *
     * @param surveyPaddingTop the value for t_survey_style.survey_padding_top
     *
     * @mbggenerated
     */
    public void setSurveyPaddingTop(String surveyPaddingTop) {
        this.surveyPaddingTop = surveyPaddingTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.survey_style_type
     *
     * @return the value of t_survey_style.survey_style_type
     *
     * @mbggenerated
     */
    public Integer getSurveyStyleType() {
        return surveyStyleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.survey_style_type
     *
     * @param surveyStyleType the value for t_survey_style.survey_style_type
     *
     * @mbggenerated
     */
    public void setSurveyStyleType(Integer surveyStyleType) {
        this.surveyStyleType = surveyStyleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.survey_width
     *
     * @return the value of t_survey_style.survey_width
     *
     * @mbggenerated
     */
    public Integer getSurveyWidth() {
        return surveyWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.survey_width
     *
     * @param surveyWidth the value for t_survey_style.survey_width
     *
     * @mbggenerated
     */
    public void setSurveyWidth(Integer surveyWidth) {
        this.surveyWidth = surveyWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.show_body_bi
     *
     * @return the value of t_survey_style.show_body_bi
     *
     * @mbggenerated
     */
    public Integer getShowBodyBi() {
        return showBodyBi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.show_body_bi
     *
     * @param showBodyBi the value for t_survey_style.show_body_bi
     *
     * @mbggenerated
     */
    public void setShowBodyBi(Integer showBodyBi) {
        this.showBodyBi = showBodyBi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.show_survey_bi
     *
     * @return the value of t_survey_style.show_survey_bi
     *
     * @mbggenerated
     */
    public Integer getShowSurveyBi() {
        return showSurveyBi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.show_survey_bi
     *
     * @param showSurveyBi the value for t_survey_style.show_survey_bi
     *
     * @mbggenerated
     */
    public void setShowSurveyBi(Integer showSurveyBi) {
        this.showSurveyBi = showSurveyBi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.show_survey_cbim
     *
     * @return the value of t_survey_style.show_survey_cbim
     *
     * @mbggenerated
     */
    public Integer getShowSurveyCbim() {
        return showSurveyCbim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.show_survey_cbim
     *
     * @param showSurveyCbim the value for t_survey_style.show_survey_cbim
     *
     * @mbggenerated
     */
    public void setShowSurveyCbim(Integer showSurveyCbim) {
        this.showSurveyCbim = showSurveyCbim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.show_survey_hbgi
     *
     * @return the value of t_survey_style.show_survey_hbgi
     *
     * @mbggenerated
     */
    public Integer getShowSurveyHbgi() {
        return showSurveyHbgi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.show_survey_hbgi
     *
     * @param showSurveyHbgi the value for t_survey_style.show_survey_hbgi
     *
     * @mbggenerated
     */
    public void setShowSurveyHbgi(Integer showSurveyHbgi) {
        this.showSurveyHbgi = showSurveyHbgi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.survey_content_bg_color_top
     *
     * @return the value of t_survey_style.survey_content_bg_color_top
     *
     * @mbggenerated
     */
    public String getSurveyContentBgColorTop() {
        return surveyContentBgColorTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.survey_content_bg_color_top
     *
     * @param surveyContentBgColorTop the value for t_survey_style.survey_content_bg_color_top
     *
     * @mbggenerated
     */
    public void setSurveyContentBgColorTop(String surveyContentBgColorTop) {
        this.surveyContentBgColorTop = surveyContentBgColorTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.show_survey_logo
     *
     * @return the value of t_survey_style.show_survey_logo
     *
     * @mbggenerated
     */
    public Integer getShowSurveyLogo() {
        return showSurveyLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.show_survey_logo
     *
     * @param showSurveyLogo the value for t_survey_style.show_survey_logo
     *
     * @mbggenerated
     */
    public void setShowSurveyLogo(Integer showSurveyLogo) {
        this.showSurveyLogo = showSurveyLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.survey_logo_image
     *
     * @return the value of t_survey_style.survey_logo_image
     *
     * @mbggenerated
     */
    public String getSurveyLogoImage() {
        return surveyLogoImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.survey_logo_image
     *
     * @param surveyLogoImage the value for t_survey_style.survey_logo_image
     *
     * @mbggenerated
     */
    public void setSurveyLogoImage(String surveyLogoImage) {
        this.surveyLogoImage = surveyLogoImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.question_option_text_color
     *
     * @return the value of t_survey_style.question_option_text_color
     *
     * @mbggenerated
     */
    public String getQuestionOptionTextColor() {
        return questionOptionTextColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.question_option_text_color
     *
     * @param questionOptionTextColor the value for t_survey_style.question_option_text_color
     *
     * @mbggenerated
     */
    public void setQuestionOptionTextColor(String questionOptionTextColor) {
        this.questionOptionTextColor = questionOptionTextColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.question_title_text_color
     *
     * @return the value of t_survey_style.question_title_text_color
     *
     * @mbggenerated
     */
    public String getQuestionTitleTextColor() {
        return questionTitleTextColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.question_title_text_color
     *
     * @param questionTitleTextColor the value for t_survey_style.question_title_text_color
     *
     * @mbggenerated
     */
    public void setQuestionTitleTextColor(String questionTitleTextColor) {
        this.questionTitleTextColor = questionTitleTextColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.survey_note_text_color
     *
     * @return the value of t_survey_style.survey_note_text_color
     *
     * @mbggenerated
     */
    public String getSurveyNoteTextColor() {
        return surveyNoteTextColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.survey_note_text_color
     *
     * @param surveyNoteTextColor the value for t_survey_style.survey_note_text_color
     *
     * @mbggenerated
     */
    public void setSurveyNoteTextColor(String surveyNoteTextColor) {
        this.surveyNoteTextColor = surveyNoteTextColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.survey_title_text_color
     *
     * @return the value of t_survey_style.survey_title_text_color
     *
     * @mbggenerated
     */
    public String getSurveyTitleTextColor() {
        return surveyTitleTextColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.survey_title_text_color
     *
     * @param surveyTitleTextColor the value for t_survey_style.survey_title_text_color
     *
     * @mbggenerated
     */
    public void setSurveyTitleTextColor(String surveyTitleTextColor) {
        this.surveyTitleTextColor = surveyTitleTextColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.survey_btn_bg_color
     *
     * @return the value of t_survey_style.survey_btn_bg_color
     *
     * @mbggenerated
     */
    public String getSurveyBtnBgColor() {
        return surveyBtnBgColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.survey_btn_bg_color
     *
     * @param surveyBtnBgColor the value for t_survey_style.survey_btn_bg_color
     *
     * @mbggenerated
     */
    public void setSurveyBtnBgColor(String surveyBtnBgColor) {
        this.surveyBtnBgColor = surveyBtnBgColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.show_sur_note
     *
     * @return the value of t_survey_style.show_sur_note
     *
     * @mbggenerated
     */
    public Integer getShowSurNote() {
        return showSurNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.show_sur_note
     *
     * @param showSurNote the value for t_survey_style.show_sur_note
     *
     * @mbggenerated
     */
    public void setShowSurNote(Integer showSurNote) {
        this.showSurNote = showSurNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.show_sur_title
     *
     * @return the value of t_survey_style.show_sur_title
     *
     * @mbggenerated
     */
    public Integer getShowSurTitle() {
        return showSurTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.show_sur_title
     *
     * @param showSurTitle the value for t_survey_style.show_sur_title
     *
     * @mbggenerated
     */
    public void setShowSurTitle(Integer showSurTitle) {
        this.showSurTitle = showSurTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.show_progressbar
     *
     * @return the value of t_survey_style.show_progressbar
     *
     * @mbggenerated
     */
    public Integer getShowProgressbar() {
        return showProgressbar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.show_progressbar
     *
     * @param showProgressbar the value for t_survey_style.show_progressbar
     *
     * @mbggenerated
     */
    public void setShowProgressbar(Integer showProgressbar) {
        this.showProgressbar = showProgressbar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_style.show_ti_num
     *
     * @return the value of t_survey_style.show_ti_num
     *
     * @mbggenerated
     */
    public Integer getShowTiNum() {
        return showTiNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_style.show_ti_num
     *
     * @param showTiNum the value for t_survey_style.show_ti_num
     *
     * @mbggenerated
     */
    public void setShowTiNum(Integer showTiNum) {
        this.showTiNum = showTiNum;
    }
}