package com.key.dwsurvey.pojo;

import java.io.Serializable;
import java.util.Date;

public class SurveyStats implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_stats.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_stats.an_avg_time
     *
     * @mbggenerated
     */
    private Integer anAvgTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_stats.an_min_time
     *
     * @mbggenerated
     */
    private Integer anMinTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_stats.answer_num
     *
     * @mbggenerated
     */
    private Integer answerNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_stats.complete_num
     *
     * @mbggenerated
     */
    private Integer completeNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_stats.effective_num
     *
     * @mbggenerated
     */
    private Integer effectiveNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_stats.first_answer
     *
     * @mbggenerated
     */
    private Date firstAnswer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_stats.handle_pass_num
     *
     * @mbggenerated
     */
    private Integer handlePassNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_stats.handle_un_pass_num
     *
     * @mbggenerated
     */
    private Integer handleUnPassNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_stats.import_num
     *
     * @mbggenerated
     */
    private Integer importNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_stats.input_num
     *
     * @mbggenerated
     */
    private Integer inputNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_stats.is_new_data
     *
     * @mbggenerated
     */
    private Integer isNewData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_stats.last_answer
     *
     * @mbggenerated
     */
    private Date lastAnswer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_stats.mobile_num
     *
     * @mbggenerated
     */
    private Integer mobileNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_stats.online_num
     *
     * @mbggenerated
     */
    private Integer onlineNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_stats.survey_id
     *
     * @mbggenerated
     */
    private String surveyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_stats.un_complete_num
     *
     * @mbggenerated
     */
    private Integer unCompleteNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_stats.un_effective_num
     *
     * @mbggenerated
     */
    private Integer unEffectiveNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_stats.un_handle_num
     *
     * @mbggenerated
     */
    private Integer unHandleNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_survey_stats
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_stats.id
     *
     * @return the value of t_survey_stats.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_stats.id
     *
     * @param id the value for t_survey_stats.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_stats.an_avg_time
     *
     * @return the value of t_survey_stats.an_avg_time
     *
     * @mbggenerated
     */
    public Integer getAnAvgTime() {
        return anAvgTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_stats.an_avg_time
     *
     * @param anAvgTime the value for t_survey_stats.an_avg_time
     *
     * @mbggenerated
     */
    public void setAnAvgTime(Integer anAvgTime) {
        this.anAvgTime = anAvgTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_stats.an_min_time
     *
     * @return the value of t_survey_stats.an_min_time
     *
     * @mbggenerated
     */
    public Integer getAnMinTime() {
        return anMinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_stats.an_min_time
     *
     * @param anMinTime the value for t_survey_stats.an_min_time
     *
     * @mbggenerated
     */
    public void setAnMinTime(Integer anMinTime) {
        this.anMinTime = anMinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_stats.answer_num
     *
     * @return the value of t_survey_stats.answer_num
     *
     * @mbggenerated
     */
    public Integer getAnswerNum() {
        return answerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_stats.answer_num
     *
     * @param answerNum the value for t_survey_stats.answer_num
     *
     * @mbggenerated
     */
    public void setAnswerNum(Integer answerNum) {
        this.answerNum = answerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_stats.complete_num
     *
     * @return the value of t_survey_stats.complete_num
     *
     * @mbggenerated
     */
    public Integer getCompleteNum() {
        return completeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_stats.complete_num
     *
     * @param completeNum the value for t_survey_stats.complete_num
     *
     * @mbggenerated
     */
    public void setCompleteNum(Integer completeNum) {
        this.completeNum = completeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_stats.effective_num
     *
     * @return the value of t_survey_stats.effective_num
     *
     * @mbggenerated
     */
    public Integer getEffectiveNum() {
        return effectiveNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_stats.effective_num
     *
     * @param effectiveNum the value for t_survey_stats.effective_num
     *
     * @mbggenerated
     */
    public void setEffectiveNum(Integer effectiveNum) {
        this.effectiveNum = effectiveNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_stats.first_answer
     *
     * @return the value of t_survey_stats.first_answer
     *
     * @mbggenerated
     */
    public Date getFirstAnswer() {
        return firstAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_stats.first_answer
     *
     * @param firstAnswer the value for t_survey_stats.first_answer
     *
     * @mbggenerated
     */
    public void setFirstAnswer(Date firstAnswer) {
        this.firstAnswer = firstAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_stats.handle_pass_num
     *
     * @return the value of t_survey_stats.handle_pass_num
     *
     * @mbggenerated
     */
    public Integer getHandlePassNum() {
        return handlePassNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_stats.handle_pass_num
     *
     * @param handlePassNum the value for t_survey_stats.handle_pass_num
     *
     * @mbggenerated
     */
    public void setHandlePassNum(Integer handlePassNum) {
        this.handlePassNum = handlePassNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_stats.handle_un_pass_num
     *
     * @return the value of t_survey_stats.handle_un_pass_num
     *
     * @mbggenerated
     */
    public Integer getHandleUnPassNum() {
        return handleUnPassNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_stats.handle_un_pass_num
     *
     * @param handleUnPassNum the value for t_survey_stats.handle_un_pass_num
     *
     * @mbggenerated
     */
    public void setHandleUnPassNum(Integer handleUnPassNum) {
        this.handleUnPassNum = handleUnPassNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_stats.import_num
     *
     * @return the value of t_survey_stats.import_num
     *
     * @mbggenerated
     */
    public Integer getImportNum() {
        return importNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_stats.import_num
     *
     * @param importNum the value for t_survey_stats.import_num
     *
     * @mbggenerated
     */
    public void setImportNum(Integer importNum) {
        this.importNum = importNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_stats.input_num
     *
     * @return the value of t_survey_stats.input_num
     *
     * @mbggenerated
     */
    public Integer getInputNum() {
        return inputNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_stats.input_num
     *
     * @param inputNum the value for t_survey_stats.input_num
     *
     * @mbggenerated
     */
    public void setInputNum(Integer inputNum) {
        this.inputNum = inputNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_stats.is_new_data
     *
     * @return the value of t_survey_stats.is_new_data
     *
     * @mbggenerated
     */
    public Integer getIsNewData() {
        return isNewData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_stats.is_new_data
     *
     * @param isNewData the value for t_survey_stats.is_new_data
     *
     * @mbggenerated
     */
    public void setIsNewData(Integer isNewData) {
        this.isNewData = isNewData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_stats.last_answer
     *
     * @return the value of t_survey_stats.last_answer
     *
     * @mbggenerated
     */
    public Date getLastAnswer() {
        return lastAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_stats.last_answer
     *
     * @param lastAnswer the value for t_survey_stats.last_answer
     *
     * @mbggenerated
     */
    public void setLastAnswer(Date lastAnswer) {
        this.lastAnswer = lastAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_stats.mobile_num
     *
     * @return the value of t_survey_stats.mobile_num
     *
     * @mbggenerated
     */
    public Integer getMobileNum() {
        return mobileNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_stats.mobile_num
     *
     * @param mobileNum the value for t_survey_stats.mobile_num
     *
     * @mbggenerated
     */
    public void setMobileNum(Integer mobileNum) {
        this.mobileNum = mobileNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_stats.online_num
     *
     * @return the value of t_survey_stats.online_num
     *
     * @mbggenerated
     */
    public Integer getOnlineNum() {
        return onlineNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_stats.online_num
     *
     * @param onlineNum the value for t_survey_stats.online_num
     *
     * @mbggenerated
     */
    public void setOnlineNum(Integer onlineNum) {
        this.onlineNum = onlineNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_stats.survey_id
     *
     * @return the value of t_survey_stats.survey_id
     *
     * @mbggenerated
     */
    public String getSurveyId() {
        return surveyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_stats.survey_id
     *
     * @param surveyId the value for t_survey_stats.survey_id
     *
     * @mbggenerated
     */
    public void setSurveyId(String surveyId) {
        this.surveyId = surveyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_stats.un_complete_num
     *
     * @return the value of t_survey_stats.un_complete_num
     *
     * @mbggenerated
     */
    public Integer getUnCompleteNum() {
        return unCompleteNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_stats.un_complete_num
     *
     * @param unCompleteNum the value for t_survey_stats.un_complete_num
     *
     * @mbggenerated
     */
    public void setUnCompleteNum(Integer unCompleteNum) {
        this.unCompleteNum = unCompleteNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_stats.un_effective_num
     *
     * @return the value of t_survey_stats.un_effective_num
     *
     * @mbggenerated
     */
    public Integer getUnEffectiveNum() {
        return unEffectiveNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_stats.un_effective_num
     *
     * @param unEffectiveNum the value for t_survey_stats.un_effective_num
     *
     * @mbggenerated
     */
    public void setUnEffectiveNum(Integer unEffectiveNum) {
        this.unEffectiveNum = unEffectiveNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_stats.un_handle_num
     *
     * @return the value of t_survey_stats.un_handle_num
     *
     * @mbggenerated
     */
    public Integer getUnHandleNum() {
        return unHandleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_stats.un_handle_num
     *
     * @param unHandleNum the value for t_survey_stats.un_handle_num
     *
     * @mbggenerated
     */
    public void setUnHandleNum(Integer unHandleNum) {
        this.unHandleNum = unHandleNum;
    }
}