package com.key.dwsurvey.pojo;

import java.io.Serializable;
import java.util.Date;

public class SurveyMailInvite implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_mail_invite.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_mail_invite.audit
     *
     * @mbggenerated
     */
    private Integer audit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_mail_invite.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_mail_invite.dw_send_user_mail
     *
     * @mbggenerated
     */
    private String dwSendUserMail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_mail_invite.dw_send_user_name
     *
     * @mbggenerated
     */
    private String dwSendUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_mail_invite.dw_survey_link
     *
     * @mbggenerated
     */
    private String dwSurveyLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_mail_invite.dw_survey_name
     *
     * @mbggenerated
     */
    private String dwSurveyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_mail_invite.error_msg
     *
     * @mbggenerated
     */
    private String errorMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_mail_invite.fail_num
     *
     * @mbggenerated
     */
    private Integer failNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_mail_invite.inbox_num
     *
     * @mbggenerated
     */
    private Integer inboxNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_mail_invite.send_num
     *
     * @mbggenerated
     */
    private Integer sendNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_mail_invite.sendcloud_msg_id
     *
     * @mbggenerated
     */
    private String sendcloudMsgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_mail_invite.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_mail_invite.subject
     *
     * @mbggenerated
     */
    private String subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_mail_invite.success_num
     *
     * @mbggenerated
     */
    private Integer successNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_mail_invite.survey_id
     *
     * @mbggenerated
     */
    private String surveyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_mail_invite.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_survey_mail_invite
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_mail_invite.id
     *
     * @return the value of t_survey_mail_invite.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_mail_invite.id
     *
     * @param id the value for t_survey_mail_invite.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_mail_invite.audit
     *
     * @return the value of t_survey_mail_invite.audit
     *
     * @mbggenerated
     */
    public Integer getAudit() {
        return audit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_mail_invite.audit
     *
     * @param audit the value for t_survey_mail_invite.audit
     *
     * @mbggenerated
     */
    public void setAudit(Integer audit) {
        this.audit = audit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_mail_invite.create_date
     *
     * @return the value of t_survey_mail_invite.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_mail_invite.create_date
     *
     * @param createDate the value for t_survey_mail_invite.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_mail_invite.dw_send_user_mail
     *
     * @return the value of t_survey_mail_invite.dw_send_user_mail
     *
     * @mbggenerated
     */
    public String getDwSendUserMail() {
        return dwSendUserMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_mail_invite.dw_send_user_mail
     *
     * @param dwSendUserMail the value for t_survey_mail_invite.dw_send_user_mail
     *
     * @mbggenerated
     */
    public void setDwSendUserMail(String dwSendUserMail) {
        this.dwSendUserMail = dwSendUserMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_mail_invite.dw_send_user_name
     *
     * @return the value of t_survey_mail_invite.dw_send_user_name
     *
     * @mbggenerated
     */
    public String getDwSendUserName() {
        return dwSendUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_mail_invite.dw_send_user_name
     *
     * @param dwSendUserName the value for t_survey_mail_invite.dw_send_user_name
     *
     * @mbggenerated
     */
    public void setDwSendUserName(String dwSendUserName) {
        this.dwSendUserName = dwSendUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_mail_invite.dw_survey_link
     *
     * @return the value of t_survey_mail_invite.dw_survey_link
     *
     * @mbggenerated
     */
    public String getDwSurveyLink() {
        return dwSurveyLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_mail_invite.dw_survey_link
     *
     * @param dwSurveyLink the value for t_survey_mail_invite.dw_survey_link
     *
     * @mbggenerated
     */
    public void setDwSurveyLink(String dwSurveyLink) {
        this.dwSurveyLink = dwSurveyLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_mail_invite.dw_survey_name
     *
     * @return the value of t_survey_mail_invite.dw_survey_name
     *
     * @mbggenerated
     */
    public String getDwSurveyName() {
        return dwSurveyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_mail_invite.dw_survey_name
     *
     * @param dwSurveyName the value for t_survey_mail_invite.dw_survey_name
     *
     * @mbggenerated
     */
    public void setDwSurveyName(String dwSurveyName) {
        this.dwSurveyName = dwSurveyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_mail_invite.error_msg
     *
     * @return the value of t_survey_mail_invite.error_msg
     *
     * @mbggenerated
     */
    public String getErrorMsg() {
        return errorMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_mail_invite.error_msg
     *
     * @param errorMsg the value for t_survey_mail_invite.error_msg
     *
     * @mbggenerated
     */
    public void setErrorMsg(String errorMsg) {
        this.errorMsg = errorMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_mail_invite.fail_num
     *
     * @return the value of t_survey_mail_invite.fail_num
     *
     * @mbggenerated
     */
    public Integer getFailNum() {
        return failNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_mail_invite.fail_num
     *
     * @param failNum the value for t_survey_mail_invite.fail_num
     *
     * @mbggenerated
     */
    public void setFailNum(Integer failNum) {
        this.failNum = failNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_mail_invite.inbox_num
     *
     * @return the value of t_survey_mail_invite.inbox_num
     *
     * @mbggenerated
     */
    public Integer getInboxNum() {
        return inboxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_mail_invite.inbox_num
     *
     * @param inboxNum the value for t_survey_mail_invite.inbox_num
     *
     * @mbggenerated
     */
    public void setInboxNum(Integer inboxNum) {
        this.inboxNum = inboxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_mail_invite.send_num
     *
     * @return the value of t_survey_mail_invite.send_num
     *
     * @mbggenerated
     */
    public Integer getSendNum() {
        return sendNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_mail_invite.send_num
     *
     * @param sendNum the value for t_survey_mail_invite.send_num
     *
     * @mbggenerated
     */
    public void setSendNum(Integer sendNum) {
        this.sendNum = sendNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_mail_invite.sendcloud_msg_id
     *
     * @return the value of t_survey_mail_invite.sendcloud_msg_id
     *
     * @mbggenerated
     */
    public String getSendcloudMsgId() {
        return sendcloudMsgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_mail_invite.sendcloud_msg_id
     *
     * @param sendcloudMsgId the value for t_survey_mail_invite.sendcloud_msg_id
     *
     * @mbggenerated
     */
    public void setSendcloudMsgId(String sendcloudMsgId) {
        this.sendcloudMsgId = sendcloudMsgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_mail_invite.status
     *
     * @return the value of t_survey_mail_invite.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_mail_invite.status
     *
     * @param status the value for t_survey_mail_invite.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_mail_invite.subject
     *
     * @return the value of t_survey_mail_invite.subject
     *
     * @mbggenerated
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_mail_invite.subject
     *
     * @param subject the value for t_survey_mail_invite.subject
     *
     * @mbggenerated
     */
    public void setSubject(String subject) {
        this.subject = subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_mail_invite.success_num
     *
     * @return the value of t_survey_mail_invite.success_num
     *
     * @mbggenerated
     */
    public Integer getSuccessNum() {
        return successNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_mail_invite.success_num
     *
     * @param successNum the value for t_survey_mail_invite.success_num
     *
     * @mbggenerated
     */
    public void setSuccessNum(Integer successNum) {
        this.successNum = successNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_mail_invite.survey_id
     *
     * @return the value of t_survey_mail_invite.survey_id
     *
     * @mbggenerated
     */
    public String getSurveyId() {
        return surveyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_mail_invite.survey_id
     *
     * @param surveyId the value for t_survey_mail_invite.survey_id
     *
     * @mbggenerated
     */
    public void setSurveyId(String surveyId) {
        this.surveyId = surveyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_mail_invite.user_id
     *
     * @return the value of t_survey_mail_invite.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_mail_invite.user_id
     *
     * @param userId the value for t_survey_mail_invite.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }
}