package com.key.dwsurvey.pojo;

import java.io.Serializable;
import java.util.Date;

public class SurveyDetail implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_detail.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_detail.an_item_least_num
     *
     * @mbggenerated
     */
    private Integer anItemLeastNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_detail.an_item_most_num
     *
     * @mbggenerated
     */
    private Integer anItemMostNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_detail.dir_id
     *
     * @mbggenerated
     */
    private String dirId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_detail.effective
     *
     * @mbggenerated
     */
    private Integer effective;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_detail.effective_ip
     *
     * @mbggenerated
     */
    private Integer effectiveIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_detail.effective_time
     *
     * @mbggenerated
     */
    private Integer effectiveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_detail.end_num
     *
     * @mbggenerated
     */
    private Integer endNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_detail.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_detail.end_type
     *
     * @mbggenerated
     */
    private Integer endType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_detail.mail_only
     *
     * @mbggenerated
     */
    private Integer mailOnly;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_detail.refresh
     *
     * @mbggenerated
     */
    private Integer refresh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_detail.refresh_num
     *
     * @mbggenerated
     */
    private Integer refreshNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_detail.rule
     *
     * @mbggenerated
     */
    private Integer rule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_detail.rule_code
     *
     * @mbggenerated
     */
    private String ruleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_detail.show_answer_da
     *
     * @mbggenerated
     */
    private Integer showAnswerDa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_detail.show_share_survey
     *
     * @mbggenerated
     */
    private Integer showShareSurvey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_detail.survey_qu_num
     *
     * @mbggenerated
     */
    private Integer surveyQuNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_detail.yn_end_num
     *
     * @mbggenerated
     */
    private Integer ynEndNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_detail.yn_end_time
     *
     * @mbggenerated
     */
    private Integer ynEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_survey_detail.survey_note
     *
     * @mbggenerated
     */
    private String surveyNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_survey_detail
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_detail.id
     *
     * @return the value of t_survey_detail.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_detail.id
     *
     * @param id the value for t_survey_detail.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_detail.an_item_least_num
     *
     * @return the value of t_survey_detail.an_item_least_num
     *
     * @mbggenerated
     */
    public Integer getAnItemLeastNum() {
        return anItemLeastNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_detail.an_item_least_num
     *
     * @param anItemLeastNum the value for t_survey_detail.an_item_least_num
     *
     * @mbggenerated
     */
    public void setAnItemLeastNum(Integer anItemLeastNum) {
        this.anItemLeastNum = anItemLeastNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_detail.an_item_most_num
     *
     * @return the value of t_survey_detail.an_item_most_num
     *
     * @mbggenerated
     */
    public Integer getAnItemMostNum() {
        return anItemMostNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_detail.an_item_most_num
     *
     * @param anItemMostNum the value for t_survey_detail.an_item_most_num
     *
     * @mbggenerated
     */
    public void setAnItemMostNum(Integer anItemMostNum) {
        this.anItemMostNum = anItemMostNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_detail.dir_id
     *
     * @return the value of t_survey_detail.dir_id
     *
     * @mbggenerated
     */
    public String getDirId() {
        return dirId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_detail.dir_id
     *
     * @param dirId the value for t_survey_detail.dir_id
     *
     * @mbggenerated
     */
    public void setDirId(String dirId) {
        this.dirId = dirId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_detail.effective
     *
     * @return the value of t_survey_detail.effective
     *
     * @mbggenerated
     */
    public Integer getEffective() {
        return effective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_detail.effective
     *
     * @param effective the value for t_survey_detail.effective
     *
     * @mbggenerated
     */
    public void setEffective(Integer effective) {
        this.effective = effective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_detail.effective_ip
     *
     * @return the value of t_survey_detail.effective_ip
     *
     * @mbggenerated
     */
    public Integer getEffectiveIp() {
        return effectiveIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_detail.effective_ip
     *
     * @param effectiveIp the value for t_survey_detail.effective_ip
     *
     * @mbggenerated
     */
    public void setEffectiveIp(Integer effectiveIp) {
        this.effectiveIp = effectiveIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_detail.effective_time
     *
     * @return the value of t_survey_detail.effective_time
     *
     * @mbggenerated
     */
    public Integer getEffectiveTime() {
        return effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_detail.effective_time
     *
     * @param effectiveTime the value for t_survey_detail.effective_time
     *
     * @mbggenerated
     */
    public void setEffectiveTime(Integer effectiveTime) {
        this.effectiveTime = effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_detail.end_num
     *
     * @return the value of t_survey_detail.end_num
     *
     * @mbggenerated
     */
    public Integer getEndNum() {
        return endNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_detail.end_num
     *
     * @param endNum the value for t_survey_detail.end_num
     *
     * @mbggenerated
     */
    public void setEndNum(Integer endNum) {
        this.endNum = endNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_detail.end_time
     *
     * @return the value of t_survey_detail.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_detail.end_time
     *
     * @param endTime the value for t_survey_detail.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_detail.end_type
     *
     * @return the value of t_survey_detail.end_type
     *
     * @mbggenerated
     */
    public Integer getEndType() {
        return endType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_detail.end_type
     *
     * @param endType the value for t_survey_detail.end_type
     *
     * @mbggenerated
     */
    public void setEndType(Integer endType) {
        this.endType = endType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_detail.mail_only
     *
     * @return the value of t_survey_detail.mail_only
     *
     * @mbggenerated
     */
    public Integer getMailOnly() {
        return mailOnly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_detail.mail_only
     *
     * @param mailOnly the value for t_survey_detail.mail_only
     *
     * @mbggenerated
     */
    public void setMailOnly(Integer mailOnly) {
        this.mailOnly = mailOnly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_detail.refresh
     *
     * @return the value of t_survey_detail.refresh
     *
     * @mbggenerated
     */
    public Integer getRefresh() {
        return refresh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_detail.refresh
     *
     * @param refresh the value for t_survey_detail.refresh
     *
     * @mbggenerated
     */
    public void setRefresh(Integer refresh) {
        this.refresh = refresh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_detail.refresh_num
     *
     * @return the value of t_survey_detail.refresh_num
     *
     * @mbggenerated
     */
    public Integer getRefreshNum() {
        return refreshNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_detail.refresh_num
     *
     * @param refreshNum the value for t_survey_detail.refresh_num
     *
     * @mbggenerated
     */
    public void setRefreshNum(Integer refreshNum) {
        this.refreshNum = refreshNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_detail.rule
     *
     * @return the value of t_survey_detail.rule
     *
     * @mbggenerated
     */
    public Integer getRule() {
        return rule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_detail.rule
     *
     * @param rule the value for t_survey_detail.rule
     *
     * @mbggenerated
     */
    public void setRule(Integer rule) {
        this.rule = rule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_detail.rule_code
     *
     * @return the value of t_survey_detail.rule_code
     *
     * @mbggenerated
     */
    public String getRuleCode() {
        return ruleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_detail.rule_code
     *
     * @param ruleCode the value for t_survey_detail.rule_code
     *
     * @mbggenerated
     */
    public void setRuleCode(String ruleCode) {
        this.ruleCode = ruleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_detail.show_answer_da
     *
     * @return the value of t_survey_detail.show_answer_da
     *
     * @mbggenerated
     */
    public Integer getShowAnswerDa() {
        return showAnswerDa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_detail.show_answer_da
     *
     * @param showAnswerDa the value for t_survey_detail.show_answer_da
     *
     * @mbggenerated
     */
    public void setShowAnswerDa(Integer showAnswerDa) {
        this.showAnswerDa = showAnswerDa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_detail.show_share_survey
     *
     * @return the value of t_survey_detail.show_share_survey
     *
     * @mbggenerated
     */
    public Integer getShowShareSurvey() {
        return showShareSurvey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_detail.show_share_survey
     *
     * @param showShareSurvey the value for t_survey_detail.show_share_survey
     *
     * @mbggenerated
     */
    public void setShowShareSurvey(Integer showShareSurvey) {
        this.showShareSurvey = showShareSurvey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_detail.survey_qu_num
     *
     * @return the value of t_survey_detail.survey_qu_num
     *
     * @mbggenerated
     */
    public Integer getSurveyQuNum() {
        return surveyQuNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_detail.survey_qu_num
     *
     * @param surveyQuNum the value for t_survey_detail.survey_qu_num
     *
     * @mbggenerated
     */
    public void setSurveyQuNum(Integer surveyQuNum) {
        this.surveyQuNum = surveyQuNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_detail.yn_end_num
     *
     * @return the value of t_survey_detail.yn_end_num
     *
     * @mbggenerated
     */
    public Integer getYnEndNum() {
        return ynEndNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_detail.yn_end_num
     *
     * @param ynEndNum the value for t_survey_detail.yn_end_num
     *
     * @mbggenerated
     */
    public void setYnEndNum(Integer ynEndNum) {
        this.ynEndNum = ynEndNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_detail.yn_end_time
     *
     * @return the value of t_survey_detail.yn_end_time
     *
     * @mbggenerated
     */
    public Integer getYnEndTime() {
        return ynEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_detail.yn_end_time
     *
     * @param ynEndTime the value for t_survey_detail.yn_end_time
     *
     * @mbggenerated
     */
    public void setYnEndTime(Integer ynEndTime) {
        this.ynEndTime = ynEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_survey_detail.survey_note
     *
     * @return the value of t_survey_detail.survey_note
     *
     * @mbggenerated
     */
    public String getSurveyNote() {
        return surveyNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_survey_detail.survey_note
     *
     * @param surveyNote the value for t_survey_detail.survey_note
     *
     * @mbggenerated
     */
    public void setSurveyNote(String surveyNote) {
        this.surveyNote = surveyNote;
    }
}