package com.key.dwsurvey.pojo;

import java.io.Serializable;
import java.util.Date;

public class SysDbBackup implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_db_backup.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_db_backup.backup_name
     *
     * @mbggenerated
     */
    private String backupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_db_backup.backup_path
     *
     * @mbggenerated
     */
    private String backupPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_db_backup.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_db_backup.des
     *
     * @mbggenerated
     */
    private String des;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_db_backup
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_db_backup.id
     *
     * @return the value of t_sys_db_backup.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_db_backup.id
     *
     * @param id the value for t_sys_db_backup.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_db_backup.backup_name
     *
     * @return the value of t_sys_db_backup.backup_name
     *
     * @mbggenerated
     */
    public String getBackupName() {
        return backupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_db_backup.backup_name
     *
     * @param backupName the value for t_sys_db_backup.backup_name
     *
     * @mbggenerated
     */
    public void setBackupName(String backupName) {
        this.backupName = backupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_db_backup.backup_path
     *
     * @return the value of t_sys_db_backup.backup_path
     *
     * @mbggenerated
     */
    public String getBackupPath() {
        return backupPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_db_backup.backup_path
     *
     * @param backupPath the value for t_sys_db_backup.backup_path
     *
     * @mbggenerated
     */
    public void setBackupPath(String backupPath) {
        this.backupPath = backupPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_db_backup.create_date
     *
     * @return the value of t_sys_db_backup.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_db_backup.create_date
     *
     * @param createDate the value for t_sys_db_backup.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_db_backup.des
     *
     * @return the value of t_sys_db_backup.des
     *
     * @mbggenerated
     */
    public String getDes() {
        return des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_db_backup.des
     *
     * @param des the value for t_sys_db_backup.des
     *
     * @mbggenerated
     */
    public void setDes(String des) {
        this.des = des;
    }
}