package com.key.dwsurvey.pojo;

import java.io.Serializable;
import java.util.Date;

public class SysEmail implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_email.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_email.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_email.is_check
     *
     * @mbggenerated
     */
    private Integer isCheck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_email.post
     *
     * @mbggenerated
     */
    private String post;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_email.send_email
     *
     * @mbggenerated
     */
    private String sendEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_email.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_email.stmp_pwd
     *
     * @mbggenerated
     */
    private String stmpPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_email.stmp_server
     *
     * @mbggenerated
     */
    private String stmpServer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_email.stmp_user
     *
     * @mbggenerated
     */
    private String stmpUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_email
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_email.id
     *
     * @return the value of t_sys_email.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_email.id
     *
     * @param id the value for t_sys_email.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_email.create_date
     *
     * @return the value of t_sys_email.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_email.create_date
     *
     * @param createDate the value for t_sys_email.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_email.is_check
     *
     * @return the value of t_sys_email.is_check
     *
     * @mbggenerated
     */
    public Integer getIsCheck() {
        return isCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_email.is_check
     *
     * @param isCheck the value for t_sys_email.is_check
     *
     * @mbggenerated
     */
    public void setIsCheck(Integer isCheck) {
        this.isCheck = isCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_email.post
     *
     * @return the value of t_sys_email.post
     *
     * @mbggenerated
     */
    public String getPost() {
        return post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_email.post
     *
     * @param post the value for t_sys_email.post
     *
     * @mbggenerated
     */
    public void setPost(String post) {
        this.post = post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_email.send_email
     *
     * @return the value of t_sys_email.send_email
     *
     * @mbggenerated
     */
    public String getSendEmail() {
        return sendEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_email.send_email
     *
     * @param sendEmail the value for t_sys_email.send_email
     *
     * @mbggenerated
     */
    public void setSendEmail(String sendEmail) {
        this.sendEmail = sendEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_email.state
     *
     * @return the value of t_sys_email.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_email.state
     *
     * @param state the value for t_sys_email.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_email.stmp_pwd
     *
     * @return the value of t_sys_email.stmp_pwd
     *
     * @mbggenerated
     */
    public String getStmpPwd() {
        return stmpPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_email.stmp_pwd
     *
     * @param stmpPwd the value for t_sys_email.stmp_pwd
     *
     * @mbggenerated
     */
    public void setStmpPwd(String stmpPwd) {
        this.stmpPwd = stmpPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_email.stmp_server
     *
     * @return the value of t_sys_email.stmp_server
     *
     * @mbggenerated
     */
    public String getStmpServer() {
        return stmpServer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_email.stmp_server
     *
     * @param stmpServer the value for t_sys_email.stmp_server
     *
     * @mbggenerated
     */
    public void setStmpServer(String stmpServer) {
        this.stmpServer = stmpServer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_email.stmp_user
     *
     * @return the value of t_sys_email.stmp_user
     *
     * @mbggenerated
     */
    public String getStmpUser() {
        return stmpUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_email.stmp_user
     *
     * @param stmpUser the value for t_sys_email.stmp_user
     *
     * @mbggenerated
     */
    public void setStmpUser(String stmpUser) {
        this.stmpUser = stmpUser;
    }
}