package com.key.dwsurvey.pojo;

import java.io.Serializable;
import java.util.Date;

public class Tracker implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tracker.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tracker.data_id
     *
     * @mbggenerated
     */
    private String dataId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tracker.data_type
     *
     * @mbggenerated
     */
    private String dataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tracker.login_name
     *
     * @mbggenerated
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tracker.operation
     *
     * @mbggenerated
     */
    private String operation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tracker.optime
     *
     * @mbggenerated
     */
    private Date optime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tracker
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tracker.id
     *
     * @return the value of tracker.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tracker.id
     *
     * @param id the value for tracker.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tracker.data_id
     *
     * @return the value of tracker.data_id
     *
     * @mbggenerated
     */
    public String getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tracker.data_id
     *
     * @param dataId the value for tracker.data_id
     *
     * @mbggenerated
     */
    public void setDataId(String dataId) {
        this.dataId = dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tracker.data_type
     *
     * @return the value of tracker.data_type
     *
     * @mbggenerated
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tracker.data_type
     *
     * @param dataType the value for tracker.data_type
     *
     * @mbggenerated
     */
    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tracker.login_name
     *
     * @return the value of tracker.login_name
     *
     * @mbggenerated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tracker.login_name
     *
     * @param loginName the value for tracker.login_name
     *
     * @mbggenerated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tracker.operation
     *
     * @return the value of tracker.operation
     *
     * @mbggenerated
     */
    public String getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tracker.operation
     *
     * @param operation the value for tracker.operation
     *
     * @mbggenerated
     */
    public void setOperation(String operation) {
        this.operation = operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tracker.optime
     *
     * @return the value of tracker.optime
     *
     * @mbggenerated
     */
    public Date getOptime() {
        return optime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tracker.optime
     *
     * @param optime the value for tracker.optime
     *
     * @mbggenerated
     */
    public void setOptime(Date optime) {
        this.optime = optime;
    }
}