package com.key.dwsurvey.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.key.dwsurvey.DTO.AnAnswerDTO;
import com.key.dwsurvey.entity.AnAnswer;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;


@Repository
public interface AnAnswerMapper extends BaseMapper<AnAnswer> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_answer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_answer
     *
     * @mbggenerated
     */
    int insert(AnAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_answer
     *
     * @mbggenerated
     */
    int insertSelective(AnAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_answer
     *
     * @mbggenerated
     */
    AnAnswer selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_answer
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AnAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_answer
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AnAnswer record);


    AnAnswerDTO findGroupStats(@Param("quId") String quId);
}