package com.key.dwsurvey.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;

import com.key.dwsurvey.DTO.AnChenFbkDTO;
import com.key.dwsurvey.entity.AnChenFbk;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface AnChenFbkMapper extends BaseMapper<AnChenFbk> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_chen_fbk
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_chen_fbk
     *
     * @mbggenerated
     */
    int insert(AnChenFbk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_chen_fbk
     *
     * @mbggenerated
     */
    int insertSelective(AnChenFbk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_chen_fbk
     *
     * @mbggenerated
     */
    AnChenFbk selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_chen_fbk
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AnChenFbk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_chen_fbk
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AnChenFbk record);


    /**
     *@description
     *@param
     *@return
     *@author suewong
     *@date 2020/7/16 10:27
    */
    List<AnChenFbkDTO> findGroupStats(String quId);
}