package com.key.dwsurvey.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.key.dwsurvey.DTO.AnChenCheckboxDTO;
import com.key.dwsurvey.entity.AnChenCheckbox;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface AnChenCheckboxMapper extends BaseMapper<AnChenCheckbox> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_chen_checkbox
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_chen_checkbox
     *
     * @mbggenerated
     */
    int insert(AnChenCheckbox record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_chen_checkbox
     *
     * @mbggenerated
     */
    int insertSelective(AnChenCheckbox record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_chen_checkbox
     *
     * @mbggenerated
     */
    AnChenCheckbox selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_chen_checkbox
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AnChenCheckbox record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_chen_checkbox
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AnChenCheckbox record);


    /**
     *@description
     *@param
     *@return
     *@author suewong
     *@date 2020/7/16 10:34
    */
    List<AnChenCheckboxDTO> findGroupStats(@Param("quId") String quId);
}