package com.key.dwsurvey.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;

import com.key.dwsurvey.DTO.AnChenScoreDTO;
import com.key.dwsurvey.entity.AnChenScore;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface AnChenScoreMapper extends BaseMapper<AnChenScore> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_chen_score
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_chen_score
     *
     * @mbggenerated
     */
    int insert(AnChenScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_chen_score
     *
     * @mbggenerated
     */
    int insertSelective(AnChenScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_chen_score
     *
     * @mbggenerated
     */
    AnChenScore selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_chen_score
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AnChenScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_chen_score
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AnChenScore record);


    /**
     *@description
     *@param
     *@return
     *@author suewong
     *@date 2020/7/16 10:41
    */
    List<AnChenScoreDTO> findGroupStats(@Param("quId") String quId);
}