package com.key.dwsurvey.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;

import com.key.dwsurvey.DTO.AnChenRadioDTO;
import com.key.dwsurvey.entity.AnChenRadio;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface AnChenRadioMapper extends BaseMapper<AnChenRadio> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_chen_radio
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_chen_radio
     *
     * @mbggenerated
     */
    int insert(AnChenRadio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_chen_radio
     *
     * @mbggenerated
     */
    int insertSelective(AnChenRadio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_chen_radio
     *
     * @mbggenerated
     */
    AnChenRadio selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_chen_radio
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AnChenRadio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_chen_radio
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AnChenRadio record);


    /**
     * @param
     * @return
     * @description
     * @author suewong
     * @date 2020/7/16 10:19
     */
    List<AnChenRadioDTO> findGroupStats(String quId);
}