package com.key.dwsurvey.mapper;


import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.key.dwsurvey.DTO.AnCheckboxDTO;
import com.key.dwsurvey.entity.AnCheckbox;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface AnCheckboxMapper extends BaseMapper<AnCheckbox> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_checkbox
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_checkbox
     *
     * @mbggenerated
     */
    int insert(AnCheckbox record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_checkbox
     *
     * @mbggenerated
     */
    int insertSelective(AnCheckbox record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_checkbox
     *
     * @mbggenerated
     */
    AnCheckbox selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_checkbox
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AnCheckbox record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_checkbox
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AnCheckbox record);


    /**
     *@description
     *@param
     *@return
     *@author suewong
     *@date 2020/7/16 11:58
    */
    List<AnCheckboxDTO> findStatsDataChart(@Param("quId") String quId);


    /**
     *@description
     *@param
     *@return
     *@author suewong
     *@date 2020/7/16 14:17
    */
    List<AnCheckboxDTO> findGroupStats(@Param("quId")String quId);
}