package com.key.dwsurvey.mapper;


import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.key.dwsurvey.entity.AnCompChenRadio;
import org.springframework.stereotype.Repository;

@Repository
public interface AnCompChenRadioMapper extends BaseMapper<AnCompChenRadio> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_comp_chen_radio
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_comp_chen_radio
     *
     * @mbggenerated
     */
    int insert(AnCompChenRadio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_comp_chen_radio
     *
     * @mbggenerated
     */
    int insertSelective(AnCompChenRadio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_comp_chen_radio
     *
     * @mbggenerated
     */
    AnCompChenRadio selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_comp_chen_radio
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AnCompChenRadio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_comp_chen_radio
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AnCompChenRadio record);
}