package com.key.dwsurvey.mapper;


import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.key.dwsurvey.DTO.AnDfillblankDTO;
import com.key.dwsurvey.entity.AnDFillblank;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface AnDFillblankMapper extends BaseMapper<AnDFillblank> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_dfillblank
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_dfillblank
     *
     * @mbggenerated
     */
    int insert(AnDFillblank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_dfillblank
     *
     * @mbggenerated
     */
    int insertSelective(AnDFillblank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_dfillblank
     *
     * @mbggenerated
     */
    AnDFillblank selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_dfillblank
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AnDFillblank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_dfillblank
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AnDFillblank record);


    List<AnDfillblankDTO> findGroupStats(@Param("quId") String quId);
}