package com.key.dwsurvey.mapper;


import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import java.util.List;

import com.key.dwsurvey.DTO.AnEnunmquDTO;
import com.key.dwsurvey.entity.AnEnumqu;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface AnEnumquMapper extends BaseMapper<AnEnumqu> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_enumqu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_enumqu
     *
     * @mbggenerated
     */
    int insert(AnEnumqu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_enumqu
     *
     * @mbggenerated
     */
    int insertSelective(AnEnumqu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_enumqu
     *
     * @mbggenerated
     */
    AnEnumqu selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_enumqu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AnEnumqu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_enumqu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AnEnumqu record);


    /**
     *@description 查询数量
     *@param
     *@return
     *@author suewong
     *@date 2020/7/15 17:10
    */
    List<AnEnunmquDTO> findGroupStats(@Param("quId") String quId);
}