package com.key.dwsurvey.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.key.dwsurvey.DTO.AnFillblankDTO;
import com.key.dwsurvey.entity.AnFillblank;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;


@Repository
public interface AnFillblankMapper extends BaseMapper<AnFillblank> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_fillblank
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_fillblank
     *
     * @mbggenerated
     */
    int insert(AnFillblank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_fillblank
     *
     * @mbggenerated
     */
    int insertSelective(AnFillblank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_fillblank
     *
     * @mbggenerated
     */
    AnFillblank selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_fillblank
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AnFillblank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_fillblank
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AnFillblank record);

    List<AnFillblank> selectPage(@Param("page")Page<AnFillblank> page, @Param("map")Map map);


    /**
     *@description 查询答案填写和未填写的数量
     *@param
     *@return
     *@author suewong
     *@date 2020/7/15 10:55
     */
    AnFillblankDTO findGroupStats(@Param("quId")String quId);
}