package com.key.dwsurvey.mapper;

import com.key.common.dao.BaseMapper;
import com.key.dwsurvey.DTO.AnRadioDTO;
import com.key.dwsurvey.entity.AnRadio;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface AnRadioMapper extends BaseMapper<AnRadio> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_radio
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_radio
     *
     * @mbggenerated
     */
    int insert(AnRadio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_radio
     *
     * @mbggenerated
     */
    int insertSelective(AnRadio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_radio
     *
     * @mbggenerated
     */
    AnRadio selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_radio
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AnRadio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_radio
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AnRadio record);


    /**
     * @param
     * @return
     * @description 根据quId
     * @author suewong
     * @date 2020/7/15 11:45
     */
    List<AnRadioDTO> findGroupStats(String quId);


    /**
     * @param
     * @return
     * @description
     * @author suewong
     * @date 2020/7/16 11:48
     */
    List<AnRadioDTO> findStatsDataChart(String quId);
}