package com.key.dwsurvey.mapper;



import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.key.dwsurvey.DTO.AnScoreDTO;
import com.key.dwsurvey.entity.AnScore;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface AnScoreMapper extends BaseMapper<AnScore> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_score
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_score
     *
     * @mbggenerated
     */
    int insert(AnScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_score
     *
     * @mbggenerated
     */
    int insertSelective(AnScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_score
     *
     * @mbggenerated
     */
    AnScore selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_score
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AnScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_score
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AnScore record);



    List<AnScoreDTO> findGroupStats(@Param("quId") String quId);
}