package com.key.dwsurvey.mapper;

import com.key.common.dao.BaseMapper;
import com.key.dwsurvey.DTO.AnyesnoAnswerDTO;
import com.key.dwsurvey.entity.AnYesno;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface AnYesnoMapper extends BaseMapper<AnYesno> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_yesno
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_yesno
     *
     * @mbggenerated
     */
    int insert(AnYesno record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_yesno
     *
     * @mbggenerated
     */
    int insertSelective(AnYesno record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_yesno
     *
     * @mbggenerated
     */
    AnYesno selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_yesno
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AnYesno record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_yesno
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AnYesno record);


    /**
     * @param
     * @return
     * @description 根据id查询答案
     * @author suewong
     * @date 2020/7/15 13:28
     */
    List<AnyesnoAnswerDTO> findGroupStats(@Param("quId") String quId);

    /**
     * @param
     * @return
     * @description 获取图表数据
     * @author suewong
     * @date 2020/7/16 11:40
     */
    List<AnyesnoAnswerDTO> findStatsDataChart(@Param("quId") String quId);
}