package com.key.dwsurvey.mapper;


import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.key.dwsurvey.entity.ImportError;
import org.springframework.stereotype.Repository;

@Repository
public interface ImportErrorMapper extends BaseMapper<ImportError> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_import_error
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_import_error
     *
     * @mbggenerated
     */
    int insert(ImportError record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_import_error
     *
     * @mbggenerated
     */
    int insertSelective(ImportError record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_import_error
     *
     * @mbggenerated
     */
    ImportError selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_import_error
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ImportError record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_import_error
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ImportError record);
}