package com.key.dwsurvey.mapper;


import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.key.dwsurvey.entity.QuChenRow;
import lombok.extern.slf4j.Slf4j;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.*;

@Repository
public interface QuChenRowMapper extends BaseMapper<QuChenRow> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qu_chen_row
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qu_chen_row
     *
     * @mbggenerated
     */
    int insert(QuChenRow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qu_chen_row
     *
     * @mbggenerated
     */
    int insertSelective(QuChenRow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qu_chen_row
     *
     * @mbggenerated
     */
    QuChenRow selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qu_chen_row
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(QuChenRow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qu_chen_row
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(QuChenRow record);


    /**
     *@description 根据quId 和visibility 查询数据
     *@param
     *@return
     *@author suewong
     *@date 2020/7/14 15:43
    */
    List<QuChenRow> selectByQuIdAndVisibility(@Param("quId")String quId,@Param("visibility") Integer visibility);

    /**
     * @description 根据orderById查找第一条数据，根据降序排序
     * @param quId
     * @return
     */
    QuChenRow findFirstByOrderByIdDesc(@Param("quId") String quId);
}