package com.key.dwsurvey.mapper;


import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.key.dwsurvey.entity.QuChenColumn;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.*;

@Repository
public interface QuChenColumnMapper extends BaseMapper<QuChenColumn> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qu_chen_column
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qu_chen_column
     *
     * @mbggenerated
     */
    int insert(QuChenColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qu_chen_column
     *
     * @mbggenerated
     */
    int insertSelective(QuChenColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qu_chen_column
     *
     * @mbggenerated
     */
    QuChenColumn selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qu_chen_column
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(QuChenColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qu_chen_column
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(QuChenColumn record);


    /**
     *@description 根据quId 和visibility 查询数据
     *@param
     *@return
     *@author suewong
     *@date 2020/7/14 16:05
    */
    List<QuChenColumn> selectByQuIdAndvisibility(@Param("quId") String quId,@Param("visibility") Integer visibility);

    /**
     * @description 根据orderById查找第一条数据，根据降序排序
     * @param quId
     * @return
     */
    QuChenColumn findFirstByOrderByIdDesc(@Param("quId") String quId);
}