package com.key.dwsurvey.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.key.dwsurvey.entity.QuCheckbox;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface QuCheckboxMapper extends BaseMapper<QuCheckbox> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qu_checkbox
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qu_checkbox
     *
     * @mbggenerated
     */
    int insert(QuCheckbox record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qu_checkbox
     *
     * @mbggenerated
     */
    int insertSelective(QuCheckbox record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qu_checkbox
     *
     * @mbggenerated
     */
    QuCheckbox selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qu_checkbox
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(QuCheckbox record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qu_checkbox
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(QuCheckbox record);


    /**
     * @param
     * @return
     * @description 根据visibility或quId 查询数据
     * @author suewong
     * @date 2020/7/14 13:52
     */
    List<QuCheckbox> selectvisibilityAndQuId( @Param("visibility") Integer visibility, @Param("quId") String quId);

    /**
     * 根据orderById查找第一条数据，根据降序排序
     * @param quId
     * @return
     */
    QuCheckbox findFirstByOrderByIdDesc(@Param("quId") String quId);
}