package com.key.dwsurvey.mapper;


import com.key.common.dao.BaseMapper;
import com.key.dwsurvey.entity.QuestionLogic;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface QuestionLogicMapper extends BaseMapper<QuestionLogic> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_logic
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_logic
     *
     * @mbggenerated
     */
    int insert(QuestionLogic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_logic
     *
     * @mbggenerated
     */
    int insertSelective(QuestionLogic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_logic
     *
     * @mbggenerated
     */
    QuestionLogic selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_logic
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(QuestionLogic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_logic
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(QuestionLogic record);


    /**
     * @param
     * @return
     * @description 根据ckQuId和visibility 查询数据
     * @author suewong
     * @date 2020/7/14 16:22
     */
    List<QuestionLogic> selectByQuIdAndVisibility(@Param("ckQuId") String ckQuId, @Param("visibility") Integer visibility);
}