package com.key.dwsurvey.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.key.dwsurvey.entity.QuestionBank;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface QuestionBankMapper extends BaseMapper<QuestionBank> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_bank
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_bank
     *
     * @mbggenerated
     */
    int insert(QuestionBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_bank
     *
     * @mbggenerated
     */
    int insertSelective(QuestionBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_bank
     *
     * @mbggenerated
     */
    QuestionBank selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_bank
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(QuestionBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_bank
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(QuestionBank record);

    QuestionBank findFirst(@Param("map")Map map);

    List<QuestionBank> selectPage(@Param("page") Page<QuestionBank> page, @Param("map")Map map);

    List<QuestionBank> findListByParentId(@Param("parentId") String parentId);
}