package com.key.dwsurvey.mapper;



import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.key.dwsurvey.entity.QuMultiFillblank;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface QuMultiFillblankMapper extends BaseMapper<QuMultiFillblank> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qu_multi_fillblank
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qu_multi_fillblank
     *
     * @mbggenerated
     */
    int insert(QuMultiFillblank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qu_multi_fillblank
     *
     * @mbggenerated
     */
    int insertSelective(QuMultiFillblank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qu_multi_fillblank
     *
     * @mbggenerated
     */
    QuMultiFillblank selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qu_multi_fillblank
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(QuMultiFillblank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qu_multi_fillblank
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(QuMultiFillblank record);


    List<QuMultiFillblank> selectByVisibilityAndQuId( @Param("visibility") Integer visibility, @Param("quId") String quId);

    /**
     * @description 根据orderById查找第一条数据，根据降序排序
     * @param quId
     * @return
     */
    QuMultiFillblank findFirstByOrderByIdDesc(@Param("quId") String quId);
}