package com.key.dwsurvey.mapper;


import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.key.dwsurvey.entity.QuOrderby;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface QuOrderbyMapper extends BaseMapper<QuOrderby> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qu_orderby
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qu_orderby
     *
     * @mbggenerated
     */
    int insert(QuOrderby record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qu_orderby
     *
     * @mbggenerated
     */
    int insertSelective(QuOrderby record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qu_orderby
     *
     * @mbggenerated
     */
    QuOrderby selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qu_orderby
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(QuOrderby record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qu_orderby
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(QuOrderby record);

    /**
     * @param
     * @return
     * @description 根据visibility 和quId 查询数据
     * @author suewong
     * @date 2020/7/14 16:15
     */
    List<QuOrderby> selectByQuIdAndVisibility(@Param("quId") String quId, @Param("visibility") Integer visibility);

    /**
     * @description 根据orderById查找第一条数据，根据降序排序
     * @param quId
     * @return
     */
    QuOrderby findFirstByOrderByIdDesc(@Param("quId") String quId);
}