package com.key.dwsurvey.mapper;

import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.key.common.dao.BaseMapper;
import com.key.dwsurvey.entity.QuRadio;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface QuRadioMapper extends BaseMapper<QuRadio> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qu_radio
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qu_radio
     *
     * @mbggenerated
     */
    int insert(QuRadio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qu_radio
     *
     * @mbggenerated
     */
    int insertSelective(QuRadio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qu_radio
     *
     * @mbggenerated
     */
    QuRadio selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qu_radio
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(QuRadio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qu_radio
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(QuRadio record);

    /**
     * @param
     * @return
     * @description 根据visibility 和quId查询数据
     * @author suewong
     * @date 2020/7/14 13:18
     */
    List<QuRadio> selectByVvisibilityAndQuId( @Param("visibility") Integer visibility,@Param("quId") String quId);

    /**
     * @description 根据orderById查找第一条数据，根据降序排序
     * @param quId
     * @return
     */
    QuRadio findFirstByOrderByIdDesc(@Param("quId") String quId);

    /**
     * 更新排序
     */
    void quOrderByIdDel1(String quId,Integer orderById);
}