package com.key.dwsurvey.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.key.dwsurvey.entity.QuScore;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface QuScoreMapper extends BaseMapper<QuScore> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qu_score
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qu_score
     *
     * @mbggenerated
     */
    int insert(QuScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qu_score
     *
     * @mbggenerated
     */
    int insertSelective(QuScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qu_score
     *
     * @mbggenerated
     */
    QuScore selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qu_score
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(QuScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qu_score
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(QuScore record);


    /**
     *@description 根据quId和visibility查询数据
     *@param
     *@return
     *@author suewong
     *@date 2020/7/14 16:11
    */
    List<QuScore> selectByQuIdAndvisibility(@Param("quId") String quId, @Param("visibility") Integer visibility);

    /**
     * @description 根据orderById查找第一条数据，根据降序排序
     * @param quId
     * @return
     */
    QuScore findFirstByOrderByIdDesc(@Param("quId") String quId);
}