package com.key.dwsurvey.mapper;

import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.baomidou.mybatisplus.core.toolkit.Constants;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.key.dwsurvey.entity.SurveyDirectory;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;


@Repository
public interface SurveyDirectoryMapper  extends BaseMapper<SurveyDirectory> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_survey_directory
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_survey_directory
     *
     * @mbggenerated
     */
    int insert(SurveyDirectory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_survey_directory
     *
     * @mbggenerated
     */
    int insertSelective(SurveyDirectory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_survey_directory
     *
     * @mbggenerated
     */
    SurveyDirectory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_survey_directory
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SurveyDirectory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_survey_directory
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SurveyDirectory record);

    List<SurveyDirectory> selectPage(@Param("page") Page<SurveyDirectory> page, @Param("map") Map<String,Object> map);

    List<SurveyDirectory> selectPage1(@Param("page") Page<SurveyDirectory> page, @Param(Constants.WRAPPER)QueryWrapper<SurveyDirectory> queryWrapper);

    List<SurveyDirectory> queryPage(Page<SurveyDirectory> page, @Param("map") Map map);

    SurveyDirectory findFirst(@Param("map")Map map);


    SurveyDirectory selectBySid(@Param("sid") String sid);
}