package com.key.dwsurvey.mapper;

import com.key.dwsurvey.pojo.SurveyMailInvite;

public interface SurveyMailInviteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_survey_mail_invite
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_survey_mail_invite
     *
     * @mbggenerated
     */
    int insert(SurveyMailInvite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_survey_mail_invite
     *
     * @mbggenerated
     */
    int insertSelective(SurveyMailInvite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_survey_mail_invite
     *
     * @mbggenerated
     */
    SurveyMailInvite selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_survey_mail_invite
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SurveyMailInvite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_survey_mail_invite
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SurveyMailInvite record);
}