package com.key.dwsurvey.mapper;


import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.key.dwsurvey.entity.SurveyStyle;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.Map;

@Repository
public interface SurveyStyleMapper extends BaseMapper<SurveyStyle> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_survey_style
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_survey_style
     *
     * @mbggenerated
     */
    int insert(SurveyStyle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_survey_style
     *
     * @mbggenerated
     */
    int insertSelective(SurveyStyle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_survey_style
     *
     * @mbggenerated
     */
    SurveyStyle selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_survey_style
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SurveyStyle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_survey_style
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SurveyStyle record);

    SurveyStyle findFirst(@Param("map")Map map);
}