package com.key.dwsurvey.mapper;

import com.key.common.dao.BaseMapper;
import com.key.dwsurvey.entity.SurveyReqUrl;
import org.springframework.stereotype.Repository;

@Repository
public interface SurveyReqUrlMapper extends BaseMapper<SurveyReqUrl> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_survey_req_url
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_survey_req_url
     *
     * @mbggenerated
     */
    int insert(SurveyReqUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_survey_req_url
     *
     * @mbggenerated
     */
    int insertSelective(SurveyReqUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_survey_req_url
     *
     * @mbggenerated
     */
    SurveyReqUrl selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_survey_req_url
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SurveyReqUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_survey_req_url
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SurveyReqUrl record);
}