package com.key.dwsurvey.mapper;

import com.key.dwsurvey.pojo.SysDbBackup;

public interface SysDbBackupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_db_backup
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_db_backup
     *
     * @mbggenerated
     */
    int insert(SysDbBackup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_db_backup
     *
     * @mbggenerated
     */
    int insertSelective(SysDbBackup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_db_backup
     *
     * @mbggenerated
     */
    SysDbBackup selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_db_backup
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysDbBackup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_db_backup
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysDbBackup record);
}