package com.key.dwsurvey.mapper;

import com.key.dwsurvey.pojo.SysEmail;

public interface SysEmailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_email
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_email
     *
     * @mbggenerated
     */
    int insert(SysEmail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_email
     *
     * @mbggenerated
     */
    int insertSelective(SysEmail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_email
     *
     * @mbggenerated
     */
    SysEmail selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_email
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysEmail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_email
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysEmail record);
}