package com.key.dwsurvey.mapper;

import com.key.dwsurvey.pojo.Tracker;

public interface TrackerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tracker
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tracker
     *
     * @mbggenerated
     */
    int insert(Tracker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tracker
     *
     * @mbggenerated
     */
    int insertSelective(Tracker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tracker
     *
     * @mbggenerated
     */
    Tracker selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tracker
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Tracker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tracker
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Tracker record);
}